import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://jgkucychrtbbeqscpwob.supabase.co';
const SUPABASE_KEY='sb_publishable_3nrRYH8KgwUXcQEpjGSMHw_Z3px-tYz';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const W='eastern-air';
let user=null,member=null,D={},page='today',projectFilter='all';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const fmt=d=>{if(!d)return'';const x=new Date(d+(/T/.test(d)?'':'T12:00:00'));return x.toLocaleDateString([], {month:'short',day:'numeric'})};
const today=()=>new Date().toLocaleDateString('en-CA');

async function init(){const {data}=await sb.auth.getSession();user=data.session?.user||null;user?await enter():renderAuth();}
sb.auth.onAuthStateChange((e,s)=>{const nu=s?.user||null;if((nu?.id||null)!==(user?.id||null)){user=nu;setTimeout(()=>user?enter():renderAuth(),0)}});

function renderAuth(){document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="auth"><div class="authCard"><div class="brand"><div class="brandMark">EA</div><div><div class="brandTitle">Eastern Air</div><div class="brandSub">COMMAND CENTER</div></div></div><h1>Sign in</h1><p class="muted">One shared workspace for jobs, assignments, follow-ups and source intelligence.</p><div id="notice"></div><label>Name</label><input id="name" placeholder="Your name"><label>Email</label><input id="email" type="email"><label>Password</label><input id="pass" type="password"><div class="row" style="margin-top:14px"><button id="login" class="btn primary grow">Sign in</button><button id="signup" class="btn grow">Create account</button></div></div></div>`;$('#login').onclick=login;$('#signup').onclick=signup;}
function notice(t,bad=false){const n=$('#notice');if(!n)return;n.className='notice'+(bad?' error':'');n.textContent=t;}
async function login(){const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#pass').value});if(error)notice(error.message,true)}
async function signup(){const {data,error}=await sb.auth.signUp({email:$('#email').value.trim(),password:$('#pass').value,options:{data:{full_name:$('#name').value.trim()}}});if(error)return notice(error.message,true);if(!data.session)notice('Account created. Confirm your email, then sign in.');}

async function enter(){const {data}=await sb.from('workspace_members').select('role,active').eq('workspace_id',W).eq('user_id',user.id).maybeSingle();member=data;if(!member)return renderJoin();await load();renderShell();}
function renderJoin(){const invite=new URLSearchParams(location.search).get('invite')||'';document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="auth"><div class="authCard"><div class="brand"><div class="brandMark">EA</div><div><div class="brandTitle">Eastern Air</div><div class="brandSub">COMMAND CENTER</div></div></div><h1>Join Eastern Air</h1><p class="muted">Signed in as ${esc(user.email)}</p><div id="notice"></div><label>Invite code</label><input id="invite" value="${esc(invite)}"><button id="accept" class="btn primary" style="width:100%;margin-top:10px">Accept invite</button><details style="margin-top:20px"><summary class="muted">First administrator setup</summary><label>One-time setup code</label><input id="bootstrap"><button id="claim" class="btn" style="width:100%;margin-top:10px">Claim admin workspace</button></details><button id="logout" class="btn" style="width:100%;margin-top:18px">Sign out</button></div></div>`;$('#accept').onclick=acceptInvite;$('#claim').onclick=claimAdmin;$('#logout').onclick=()=>sb.auth.signOut();}
async function acceptInvite(){const {data,error}=await sb.rpc('accept_workspace_invite',{p_token:$('#invite').value.trim()});if(error||!data)return notice(error?.message||'Invite is invalid or expired.',true);location.href=location.pathname;}
async function claimAdmin(){const {data,error}=await sb.rpc('claim_first_admin',{p_token:$('#bootstrap').value.trim()});if(error||!data)return notice(error?.message||'Setup code did not work.',true);location.href=location.pathname;}

async function load(){const qs=await Promise.all([
 sb.from('projects').select('*').eq('workspace_id',W).eq('active',true).order('sort_order'),
 sb.from('work_categories').select('*').eq('workspace_id',W).eq('active',true).order('sort_order'),
 sb.from('people').select('*').eq('workspace_id',W).eq('active',true).order('name'),
 sb.from('items').select('*').eq('workspace_id',W).eq('active',true).order('updated_at',{ascending:false}),
 sb.from('item_management').select('*').eq('workspace_id',W),
 sb.from('item_assignees').select('*'),
 sb.from('user_item_preferences').select('*').eq('user_id',user.id),
 sb.from('item_watchers').select('*').eq('user_id',user.id),
 sb.from('profiles').select('id,display_name,email'),
 sb.from('workspace_members').select('workspace_id,user_id,role,active').eq('workspace_id',W)
]);
 D={projects:qs[0].data||[],categories:qs[1].data||[],people:qs[2].data||[],items:qs[3].data||[],mgmt:qs[4].data||[],assign:qs[5].data||[],prefs:qs[6].data||[],watchers:qs[7].data||[],profiles:qs[8].data||[],members:qs[9].data||[]};
}
function maps(){return{p:Object.fromEntries(D.projects.map(x=>[x.id,x])),c:Object.fromEntries(D.categories.map(x=>[x.id,x])),m:Object.fromEntries(D.mgmt.map(x=>[x.item_id,x])),pref:Object.fromEntries(D.prefs.map(x=>[x.item_id,x]))}}
function effective(i,M){const m=M.m[i.id]||{};return{project:m.project_id_override||i.project_id,category:m.category_id_override||i.category_id,title:m.title_override||i.title,priority:m.priority_override||i.priority,due:m.due_override||i.due_at,status:m.status||'inbox',follow:m.follow_up_at,note:m.shared_note}}
function ownerFor(id){const a=D.assign.find(x=>x.item_id===id&&x.active&&x.is_primary);return a?D.people.find(p=>p.id===a.person_id):null}
function myPerson(){return D.people.find(x=>x.linked_user_id===user.id)}
function visibleProject(i,M){return projectFilter==='all'||effective(i,M).project===projectFilter}
function mine(i,M){const o=ownerFor(i.id),w=D.watchers.some(x=>x.item_id===i.id),pref=M.pref[i.id];return !(pref?.dismissed_from_live)&&((o&&o.linked_user_id===user.id)||!o||w)}
function active(i,M){return effective(i,M).status!=='done'}

function renderShell(){document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="shell"><header class="top"><div class="topIn"><div class="brandRow"><div class="brand"><div class="brandMark">EA</div><div><div class="brandTitle">Command Center</div><div class="brandSub">HOSTED • SHARED</div></div></div><div class="userPill">${esc(user.email)} • ${esc(member.role)}</div></div><div id="projectChips" class="chips"></div></div></header><main id="main" class="main"></main><nav class="bottom"><div class="bottomIn">${[['today','⌂','Today'],['mine','✓','My Work'],['assigned','→','Assigned'],['jobs','▦','Jobs'],['team','♟','Team']].map(x=>`<button class="navBtn" data-page="${x[0]}"><span class="navIcon">${x[1]}</span>${x[2]}</button>`).join('')}</div></nav><div id="modalWrap" class="modalWrap"><div id="modal" class="modal"></div></div></div>`;renderProjectChips();document.querySelectorAll('.navBtn').forEach(b=>b.onclick=()=>{page=b.dataset.page;renderPage()});renderPage();}
function renderProjectChips(){const a=[`<button class="chip ${projectFilter==='all'?'active':''}" data-p="all">All Jobs</button>`].concat(D.projects.filter(x=>x.id!=='other-work').map(x=>`<button class="chip ${projectFilter===x.id?'active':''}" data-p="${x.id}">${esc(x.name.replace(' Street',''))}</button>`));$('#projectChips').innerHTML=a.join('');document.querySelectorAll('#projectChips .chip').forEach(b=>b.onclick=()=>{projectFilter=b.dataset.p;renderProjectChips();renderPage()});}
function head(title,sub,add=true){return `<div class="pageHead"><div><h1>${esc(title)}</h1><div class="muted">${esc(sub)}</div></div><div class="pageActions">${add?'<button class="btn primary" id="quickAdd">+ Add</button>':''}</div></div>`}
function statusOptions(v){return ['inbox','assigned','watching','working','waiting','follow_up','needs_review','snoozed','done'].map(s=>`<option value="${s}" ${v===s?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}
function card(i,M){const e=effective(i,M),o=ownerFor(i.id),p=M.p[e.project],c=M.c[e.category],over=e.due&&e.due<today()&&e.status!=='done';return `<article class="card"><div class="cardTop"><div class="grow"><div class="title">${esc(e.title)}</div><div class="meta"><span class="pill">${esc(p?.name||'No job')}</span><span class="pill">${esc(c?.name||'General')}</span><span class="pill ${esc(e.priority)}">${esc(e.priority)}</span><span class="pill">${esc(o?.name||'Unassigned')}</span></div></div><div class="due ${over?'over':''}">${esc(fmt(e.due))}</div></div><div class="cardActions"><select class="selectSmall statusQuick" data-id="${i.id}">${statusOptions(e.status)}</select><button class="btn small manage" data-id="${i.id}">Manage</button><button class="btn small commentBtn" data-id="${i.id}">Comment</button></div></article>`}
function kpis(arr,M){const overdue=arr.filter(i=>effective(i,M).due&&effective(i,M).due<today()&&active(i,M)).length,review=arr.filter(i=>effective(i,M).status==='needs_review').length,wait=arr.filter(i=>['waiting','follow_up'].includes(effective(i,M).status)).length,un=arr.filter(i=>!ownerFor(i.id)&&active(i,M)).length;return `<div class="kpis"><div class="kpi"><strong>${overdue}</strong><span>OVERDUE</span></div><div class="kpi"><strong>${review}</strong><span>NEEDS REVIEW</span></div><div class="kpi"><strong>${wait}</strong><span>WAIT / FOLLOW-UP</span></div><div class="kpi"><strong>${un}</strong><span>UNASSIGNED</span></div></div>`}
function wireCards(){document.querySelectorAll('.manage').forEach(b=>b.onclick=()=>openManage(b.dataset.id,false));document.querySelectorAll('.commentBtn').forEach(b=>b.onclick=()=>openManage(b.dataset.id,true));document.querySelectorAll('.statusQuick').forEach(s=>s.onchange=()=>setStatus(s.dataset.id,s.value));}
function wireAdd(){if($('#quickAdd'))$('#quickAdd').onclick=openAdd}
function renderPage(){document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='today')renderToday();if(page==='mine')renderMine();if(page==='assigned')renderAssigned();if(page==='jobs')renderJobs();if(page==='team')renderTeam();}
function renderToday(){const M=maps(),base=D.items.filter(i=>visibleProject(i,M)&&mine(i,M)&&active(i,M)),focus=base.filter(i=>{const e=effective(i,M);return ['inbox','needs_review'].includes(e.status)||(e.due&&e.due<=today())||(e.follow&&e.follow<=today())});$('#main').innerHTML=head('Today','Only what needs attention now.')+kpis(base,M)+`<div class="section"><div class="sectionTitle">Attention</div><div class="cards">${focus.length?focus.map(i=>card(i,M)).join(''):'<div class="empty">Nothing urgent in your live queue.</div>'}</div></div>`;wireAdd();wireCards();}
function renderMine(){const M=maps(),arr=D.items.filter(i=>visibleProject(i,M)&&mine(i,M)&&active(i,M));$('#main').innerHTML=head('My Work','Assigned to you, unassigned team inbox, and items you watch.')+kpis(arr,M)+`<div class="cards">${arr.length?arr.map(i=>card(i,M)).join(''):'<div class="empty">Your live queue is clear.</div>'}</div>`;wireAdd();wireCards();}
function renderAssigned(){const M=maps(),me=myPerson(),arr=D.items.filter(i=>visibleProject(i,M)&&active(i,M)&&ownerFor(i.id)&&ownerFor(i.id).id!==me?.id);$('#main').innerHTML=head('Assigned to Others','Work owned by someone else.')+`<div class="cards">${arr.length?arr.map(i=>card(i,M)).join(''):'<div class="empty">No work assigned to other people yet.</div>'}</div>`;wireAdd();wireCards();}
function renderJobs(){const M=maps(),jobs=D.projects.filter(p=>p.id!=='other-work'&&(projectFilter==='all'||p.id===projectFilter));$('#main').innerHTML=head('Jobs','Every active job in one place.')+`<div class="jobGrid">${jobs.map(p=>{const a=D.items.filter(i=>effective(i,M).project===p.id&&active(i,M));return `<div class="jobCard"><div class="jobName">${esc(p.name)}</div><div class="jobStats"><div><b>${a.length}</b><span>ACTIVE</span></div><div><b>${a.filter(i=>effective(i,M).status==='needs_review').length}</b><span>REVIEW</span></div><div><b>${a.filter(i=>!ownerFor(i.id)).length}</b><span>UNASSIGNED</span></div></div><button class="btn small jobOpen" data-p="${p.id}" style="margin-top:12px">Open job</button></div>`}).join('')}</div>`;wireAdd();document.querySelectorAll('.jobOpen').forEach(b=>b.onclick=()=>{projectFilter=b.dataset.p;page='mine';renderProjectChips();renderPage()});}
function renderTeam(){const M=maps();$('#main').innerHTML=head('Team','Assignments are shared. Personal live queues stay personal.',false)+`<div class="row" style="margin-bottom:12px"><button class="btn" id="addPerson">+ Person</button>${member.role==='admin'?'<button class="btn primary" id="inviteUser">Invite login</button>':''}<button class="btn" id="logoutTop">Sign out</button></div>${D.people.map(p=>{const a=D.items.filter(i=>ownerFor(i.id)?.id===p.id&&active(i,M));return `<div class="personBlock"><div class="row"><div class="grow"><div class="personName">${esc(p.name)}</div><div class="personStats">${a.length} active • ${p.linked_user_id?'login connected':'no login yet'}</div></div><button class="btn small personOpen" data-person="${p.id}">View work</button></div></div>`}).join('')}`;$('#logoutTop').onclick=()=>sb.auth.signOut();$('#addPerson').onclick=openAddPerson;if($('#inviteUser'))$('#inviteUser').onclick=openInvite;document.querySelectorAll('.personOpen').forEach(b=>b.onclick=()=>showPersonWork(b.dataset.person));}

async function setStatus(id,status){const old=D.mgmt.find(x=>x.item_id===id)||{};const row={...old,item_id:id,workspace_id:W,status,updated_by:user.id,updated_at:new Date().toISOString(),resolved_at:status==='done'?new Date().toISOString():null,resolved_by:status==='done'?user.id:null};const {error}=await sb.from('item_management').upsert(row,{onConflict:'item_id'});if(error)return alert(error.message);await reload();}
function openModal(html){$('#modal').innerHTML=html;$('#modalWrap').classList.add('open');$('#modalWrap').onclick=e=>{if(e.target.id==='modalWrap')closeModal()};if($('#closeModal'))$('#closeModal').onclick=closeModal}
function closeModal(){$('#modalWrap').classList.remove('open')}
const projectOptions=sel=>D.projects.map(p=>`<option value="${p.id}" ${sel===p.id?'selected':''}>${esc(p.name)}</option>`).join('');
const categoryOptions=sel=>D.categories.map(c=>`<option value="${c.id}" ${sel===c.id?'selected':''}>${esc(c.name)}</option>`).join('');
const peopleOptions=sel=>'<option value="">Unassigned</option>'+D.people.map(p=>`<option value="${p.id}" ${sel===p.id?'selected':''}>${esc(p.name)}</option>`).join('');
function openAdd(){openModal(`<div class="modalHead"><h2>Add Work</h2><button class="close" id="closeModal">×</button></div><label>What needs to happen?</label><input id="aTitle"><div class="formGrid"><div><label>Job</label><select id="aProject">${projectOptions(projectFilter==='all'?D.projects[0]?.id:projectFilter)}</select></div><div><label>Category</label><select id="aCategory">${categoryOptions('general')}</select></div><div><label>Priority</label><select id="aPriority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></div><div><label>Due</label><input id="aDue" type="date"></div></div><label>Assign to</label><select id="aOwner">${peopleOptions('')}</select><label>Notes</label><textarea id="aDesc"></textarea><button class="btn primary" id="saveAdd" style="width:100%;margin-top:14px">Add to Command Center</button>`);$('#saveAdd').onclick=saveAdd;}
async function saveAdd(){const category=$('#aCategory').value,row={workspace_id:W,project_id:$('#aProject').value,title:$('#aTitle').value.trim(),description:$('#aDesc').value.trim()||null,category_id:category,category,priority:$('#aPriority').value,due_at:$('#aDue').value||null,origin:'command_center',confidence:'confirmed',created_by:user.id};if(!row.title)return alert('Add a title.');const {data,error}=await sb.from('items').insert(row).select().single();if(error)return alert(error.message);await sb.from('item_management').insert({item_id:data.id,workspace_id:W,status:'inbox',updated_by:user.id});if($('#aOwner').value)await sb.rpc('assign_item',{p_item_id:data.id,p_person_id:$('#aOwner').value,p_note:'Assigned when created',p_keep_watching:false});closeModal();await reload();}
async function openManage(id,commentsOnly){const M=maps(),i=D.items.find(x=>x.id===id),e=effective(i,M),o=ownerFor(id);const {data:comments=[]}=await sb.from('item_comments').select('*').eq('item_id',id).order('created_at');const prof=Object.fromEntries(D.profiles.map(x=>[x.id,x]));openModal(`<div class="modalHead"><div class="grow"><div class="muted">${esc(M.p[e.project]?.name||'')}</div><h2>${esc(e.title)}</h2></div><button class="close" id="closeModal">×</button></div>${commentsOnly?'':`<div class="formGrid"><div><label>Job</label><select id="mProject">${projectOptions(e.project)}</select></div><div><label>Category</label><select id="mCategory">${categoryOptions(e.category)}</select></div><div><label>Status</label><select id="mStatus">${statusOptions(e.status)}</select></div><div><label>Priority</label><select id="mPriority">${['low','medium','high','critical'].map(s=>`<option ${e.priority===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label>Due</label><input id="mDue" type="date" value="${esc(e.due||'')}"></div><div><label>Follow up</label><input id="mFollow" type="date" value="${esc(e.follow||'')}"></div></div><label>Assign / hand off to</label><select id="mOwner">${peopleOptions(o?.id||'')}</select><label>Shared note</label><textarea id="mNote">${esc(e.note||'')}</textarea><label class="toggleline"><input id="mWatch" type="checkbox" ${D.watchers.some(x=>x.item_id===id)?'checked':''}>Keep this in my live view after assigning it to someone else</label><div class="row" style="margin-top:12px"><button class="btn primary grow" id="saveManage">Save</button><button class="btn grow" id="dismissMine">Remove from my live view</button></div><hr style="border:0;border-top:1px solid var(--line);margin:20px 0">`}<div class="sectionTitle">Conversation</div>${comments.length?comments.map(c=>`<div class="comment"><div class="commentName">${esc(prof[c.author_user_id]?.display_name||prof[c.author_user_id]?.email||'Team')} • ${fmt(c.created_at)}</div><div class="commentBody">${esc(c.body)}</div></div>`).join(''):'<div class="muted">No comments yet.</div>'}<label>Add comment</label><textarea id="newComment"></textarea><button class="btn" id="sendComment" style="width:100%">Post comment</button>`);if(!commentsOnly){$('#saveManage').onclick=()=>saveManage(id,o?.id||'');$('#dismissMine').onclick=()=>dismissMine(id)}$('#sendComment').onclick=()=>postComment(id);}
async function saveManage(id,oldOwner){const old=D.mgmt.find(x=>x.item_id===id)||{},status=$('#mStatus').value,row={...old,item_id:id,workspace_id:W,status,project_id_override:$('#mProject').value,category_id_override:$('#mCategory').value,priority_override:$('#mPriority').value,due_override:$('#mDue').value||null,follow_up_at:$('#mFollow').value||null,shared_note:$('#mNote').value.trim()||null,updated_by:user.id,updated_at:new Date().toISOString(),resolved_at:status==='done'?new Date().toISOString():null,resolved_by:status==='done'?user.id:null};const {error}=await sb.from('item_management').upsert(row,{onConflict:'item_id'});if(error)return alert(error.message);const owner=$('#mOwner').value;if(owner&&owner!==oldOwner){const r=await sb.rpc('assign_item',{p_item_id:id,p_person_id:owner,p_note:$('#mNote').value.trim()||null,p_keep_watching:$('#mWatch').checked});if(r.error)return alert(r.error.message)}closeModal();await reload();}
async function dismissMine(id){const old=D.prefs.find(x=>x.item_id===id)||{};const {error}=await sb.from('user_item_preferences').upsert({...old,user_id:user.id,item_id:id,dismissed_from_live:true,updated_at:new Date().toISOString()},{onConflict:'user_id,item_id'});if(error)return alert(error.message);closeModal();await reload();}
async function postComment(id){const body=$('#newComment').value.trim();if(!body)return;const {error}=await sb.from('item_comments').insert({workspace_id:W,item_id:id,author_user_id:user.id,body});if(error)return alert(error.message);await load();openManage(id,true);}
function openAddPerson(){openModal(`<div class="modalHead"><h2>Add Person</h2><button class="close" id="closeModal">×</button></div><label>Name</label><input id="pName"><label>Email (optional)</label><input id="pEmail" type="email"><p class="muted">You can assign work before they have a login. If they later join with the same email, the login attaches to this person.</p><button class="btn primary" id="savePerson" style="width:100%">Add person</button>`);$('#savePerson').onclick=savePerson;}
async function savePerson(){const name=$('#pName').value.trim(),email=$('#pEmail').value.trim()||null;if(!name)return alert('Name is required.');const {error}=await sb.from('people').insert({workspace_id:W,name,email,source_kind:'command_center'});if(error)return alert(error.message);closeModal();await reload();}
function openInvite(){openModal(`<div class="modalHead"><h2>Invite Login</h2><button class="close" id="closeModal">×</button></div><label>Email</label><input id="iEmail" type="email"><label>Role</label><select id="iRole"><option value="member">Member — manage work</option><option value="viewer">Viewer — read only</option><option value="manager">Manager</option><option value="admin">Admin</option></select><button class="btn primary" id="makeInvite" style="width:100%;margin-top:14px">Create private invite link</button><div id="inviteResult"></div>`);$('#makeInvite').onclick=makeInvite;}
async function makeInvite(){const {data,error}=await sb.rpc('create_workspace_invite',{p_email:$('#iEmail').value.trim(),p_role:$('#iRole').value,p_expires_days:7});if(error)return alert(error.message);const link=location.origin+location.pathname+'?invite='+encodeURIComponent(data);$('#inviteResult').innerHTML=`<label>Invite link</label><textarea id="inviteLink" readonly>${esc(link)}</textarea><button class="btn" id="copyInvite" style="width:100%">Copy link</button>`;$('#copyInvite').onclick=async()=>{await navigator.clipboard.writeText(link);$('#copyInvite').textContent='Copied'};}
function showPersonWork(personId){const M=maps(),p=D.people.find(x=>x.id===personId),arr=D.items.filter(i=>ownerFor(i.id)?.id===personId&&active(i,M));openModal(`<div class="modalHead"><div><div class="muted">Assigned Work</div><h2>${esc(p?.name||'')}</h2></div><button class="close" id="closeModal">×</button></div><div class="cards">${arr.length?arr.map(i=>card(i,M)).join(''):'<div class="empty">Nothing active.</div>'}</div>`);wireCards();}
async function reload(){await load();renderPage();}
init();
