import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const URL='https://jgkucychrtbbeqscpwob.supabase.co';
const KEY='sb_publishable_3nrRYH8KgwUXcQEpjGSMHw_Z3px-tYz';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let cursor=new Date(), mode='month', selectedProject='all', projects=[], milestones=[];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const iso=d=>d.toLocaleDateString('en-CA');
const today=()=>iso(new Date());
const fmt=d=>d?new Date(String(d).slice(0,10)+'T12:00:00').toLocaleDateString([],{month:'short',day:'numeric'}):'';
const fmtLong=d=>d?new Date(String(d).slice(0,10)+'T12:00:00').toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}):'';
const pname=id=>projects.find(p=>p.id===id)?.name||'Other';
async function load(){const [p,m]=await Promise.all([sb.from('projects').select('id,name,sort_order').eq('workspace_id','eastern-air').eq('active',true).order('sort_order'),sb.from('schedule_milestones').select('*').eq('workspace_id','eastern-air').order('planned_date')]);projects=p.data||[];milestones=m.data||[];}
function selected(){return milestones.filter(m=>selectedProject==='all'||m.project_id===selectedProject)}
function confidence(m){return (m.confidence||'source_says').replaceAll('_',' ')}
function row(m){return `<div class="ccScheduleRow ${['at_risk','delayed'].includes(m.status)?'risk':''}"><div class="ccScheduleDate">${m.planned_date?esc(fmtLong(m.planned_date)):'TBD'}</div><div><div class="ccScheduleTitle">${esc(m.title)}</div><div class="ccScheduleMeta"><span>${esc(pname(m.project_id))}</span>${m.floor?`<span>${esc(m.floor)}</span>`:''}${m.category?`<span>${esc(m.category)}</span>`:''}<span>${esc(confidence(m))}</span><span>${esc((m.status||'planned').replaceAll('_',' '))}</span></div>${m.notes?`<div class="ccScheduleNote">${esc(m.notes)}</div>`:''}</div></div>`}
function install(){const nav=document.querySelector('.navBtn[data-page="schedule"]'); if(!nav)return false; nav.querySelector('.navIcon').textContent='▣'; nav.childNodes[nav.childNodes.length-1].textContent='Calendar'; nav.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();$$('.navBtn').forEach(b=>b.classList.remove('active'));nav.classList.add('active');await load();render();},{capture:true}); return true;}
function render(){const main=$('#main'); if(!main)return; main.innerHTML=`<div class="pageHead"><div><h1>Calendar & Schedule</h1><div class="muted">Project-cycle dates, lookahead milestones and long-lead commitments.</div></div></div><div class="ccCalToolbar"><select id="ccCalProject"><option value="all">All Jobs</option>${projects.filter(p=>p.id!=='other-work').map(p=>`<option value="${p.id}" ${selectedProject===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><div class="ccModeGroup"><button data-ccmode="month" class="chip ${mode==='month'?'active':''}">Month</button><button data-ccmode="upcoming" class="chip ${mode==='upcoming'?'active':''}">Upcoming</button><button data-ccmode="cycle" class="chip ${mode==='cycle'?'active':''}">Cycle</button></div></div><div id="ccCalBody"></div>`; $('#ccCalProject').onchange=e=>{selectedProject=e.target.value;renderBody()};$$('[data-ccmode]').forEach(b=>b.onclick=()=>{mode=b.dataset.ccmode;render()});renderBody()}
function renderBody(){if(mode==='month')renderMonth(); else if(mode==='upcoming')renderUpcoming(); else renderCycle()}
function renderMonth(){const body=$('#ccCalBody'),arr=selected(),y=cursor.getFullYear(),mo=cursor.getMonth(),first=new Date(y,mo,1),last=new Date(y,mo+1,0),start=new Date(first);start.setDate(first.getDate()-first.getDay());const end=new Date(last);end.setDate(last.getDate()+(6-last.getDay()));let cells='';for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const ds=iso(d),events=arr.filter(m=>m.planned_date===ds),outside=d.getMonth()!==mo;cells+=`<button class="ccDay ${outside?'outside':''} ${ds===today()?'today':''}" data-date="${ds}"><span class="ccDayNum">${d.getDate()}</span>${events.slice(0,3).map(e=>`<span class="ccEvent">${esc(e.title)}</span>`).join('')}${events.length>3?`<span class="ccMore">+${events.length-3}</span>`:''}</button>`}body.innerHTML=`<div class="ccMonthHead"><button class="btn small" id="ccPrev">‹</button><strong>${esc(first.toLocaleDateString([],{month:'long',year:'numeric'}))}</strong><button class="btn small" id="ccNext">›</button><button class="btn small" id="ccToday">Today</button></div><div class="ccWeek"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="ccMonthGrid">${cells}</div>`;$('#ccPrev').onclick=()=>{cursor=new Date(y,mo-1,1);renderMonth()};$('#ccNext').onclick=()=>{cursor=new Date(y,mo+1,1);renderMonth()};$('#ccToday').onclick=()=>{cursor=new Date();renderMonth()};$$('.ccDay').forEach(b=>b.onclick=()=>showDay(b.dataset.date,arr.filter(m=>m.planned_date===b.dataset.date)))}
function renderUpcoming(){const arr=selected().filter(m=>m.planned_date&&m.planned_date>=today()).sort((a,b)=>a.planned_date.localeCompare(b.planned_date));$('#ccCalBody').innerHTML=`<div class="ccCount">${arr.length} upcoming milestone${arr.length===1?'':'s'}</div>${arr.length?arr.slice(0,250).map(row).join(''):'<div class="empty">No verified upcoming dates for this job yet.</div>'}`}
function renderCycle(){const arr=selected();const groups={};arr.forEach(m=>{const k=m.floor||m.category||'General';(groups[k]??=[]).push(m)});$('#ccCalBody').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="ccCycleGroup"><div class="sectionTitle">${esc(k)}</div>${v.sort((a,b)=>(a.planned_date||'9999').localeCompare(b.planned_date||'9999')).map(row).join('')}</div>`).join('')||'<div class="empty">No cycle data is loaded for this project yet.</div>'}
function showDay(date,events){let wrap=$('#ccDayModal');if(!wrap){wrap=document.createElement('div');wrap.id='ccDayModal';wrap.className='ccDayModal';document.body.appendChild(wrap)}wrap.innerHTML=`<div class="ccDaySheet"><div class="modalHead"><div><div class="muted">Schedule</div><h2>${esc(fmtLong(date))}</h2></div><button class="close" id="ccClose">×</button></div>${events.length?events.map(row).join(''):'<div class="empty">No schedule events this day.</div>'}</div>`;wrap.classList.add('open');$('#ccClose').onclick=()=>wrap.classList.remove('open');wrap.onclick=e=>{if(e.target===wrap)wrap.classList.remove('open')}}
function boot(){let tries=0;const t=setInterval(()=>{tries++;if(install()||tries>80)clearInterval(t)},250)}
boot();
