import { searchBrain, resultTypeLabel } from '../core/brain-search.mjs';
import { esc, fmtDate, fmtDateTime, human, openModal, qs, qsa, toast } from '../ui/dom.mjs';
import { sourceList } from '../ui/source-panel.mjs';

function sourceHealth(state){
  const now=Date.now(),rows=[];
  for(const cfg of state.raw.sourceConfigs??[]){
    if(state.projectScope!=='all'&&cfg.project_id!==state.projectScope)continue;
    const sources=(state.raw.sourceRecords??[]).filter(s=>s.project_id===cfg.project_id&&s.source_system===cfg.source_system&&!s.is_historical);
    const latest=sources.map(s=>s.source_updated_at||s.last_seen_at).filter(Boolean).sort().at(-1)||null;
    const success=cfg.last_success_at||null,stamp=success||latest;
    const hours=stamp?Math.round((now-new Date(stamp).getTime())/3600000):null;
    const stateLabel=cfg.last_error?'error':success?'live':'snapshot';
    rows.push({...cfg,projectName:state.maps.projects[cfg.project_id]?.name||cfg.project_id,count:sources.length,latest,hours,stateLabel});
  }
  return rows;
}
function healthCard(r){return `<article class="brainHealth ${esc(r.stateLabel)}"><div><strong>${esc(r.projectName)}</strong><span>${esc(human(r.source_system))}</span></div><div class="healthState">${r.stateLabel==='error'?'SYNC ERROR':r.stateLabel==='live'?'LIVE SYNC':'SNAPSHOT'}</div><small>${r.count} records${r.hours!==null?` · ${r.hours}h since latest`:''}</small>${r.last_error?`<p>${esc(r.last_error)}</p>`:''}</article>`}
function suggestionCard(s,state){const p=state.maps.projects[s.project_id];return `<article class="brainSuggestion"><div class="chipRow"><span class="contextChip">${esc(p?.name||'No Job')}</span><span class="priorityChip ${esc(s.priority)}">${esc(human(s.priority))}</span><span class="confidence ${esc(s.confidence)}">${esc(human(s.confidence))}</span></div><h3>${esc(s.title)}</h3><p>${esc(s.reason)}</p>${s.suggested_action?`<div class="suggestedAction"><strong>Suggested:</strong> ${esc(s.suggested_action)}</div>`:''}<div class="rowActions"><button class="btn primary small" data-accept-suggestion="${esc(s.id)}">Add to My Work</button><button class="btn secondary small" data-dismiss-suggestion="${esc(s.id)}">Dismiss</button></div></article>`}
function commitmentCard(c,state){const p=state.maps.projects[c.project_id],overdue=c.due_at&&String(c.due_at).slice(0,10)<new Date().toLocaleDateString('en-CA');return `<article class="brainCommitment ${overdue?'overdue':''}"><div class="chipRow"><span class="contextChip">${esc(p?.name||'No Job')}</span><span class="statusChip ${esc(c.status)}">${esc(human(c.status))}</span>${c.confidence?`<span class="confidence ${esc(c.confidence)}">${esc(human(c.confidence))}</span>`:''}</div><h3>${esc(c.commitment_text)}</h3><p>${esc([c.from_person||c.from_party,c.to_person||c.to_party].filter(Boolean).join(' → '))}</p>${c.due_at?`<div class="commitDue ${overdue?'badText':''}">Due ${esc(fmtDate(c.due_at))}</div>`:''}<div class="rowActions"><button class="btn secondary small" data-resolve-commitment="${esc(c.id)}">Resolve</button></div></article>`}
function topicCard(t,state){const p=state.maps.projects[t.project_id],count=(state.raw.topicSources??[]).filter(x=>x.topic_id===t.id).length;return `<article class="brainTopic"><div class="chipRow"><span class="contextChip">${esc(p?.name||'No Job')}</span><span class="contextChip">${esc(human(t.topic_type))}</span><span class="attentionBadge ${esc(t.attention_state)}">${esc(human(t.attention_state))}</span><span class="confidence ${esc(t.confidence)}">${esc(human(t.confidence))}</span></div><h3>${esc(t.title)}</h3>${t.summary?`<p>${esc(t.summary)}</p>`:''}<div class="topicFoot"><span>${count} linked source${count===1?'':'s'}</span><button class="btn secondary small" data-open-topic="${esc(t.id)}">Open Topic</button></div></article>`}
function deltaCard(d,state){const p=state.maps.projects[d.project_id];return `<article class="brainDelta"><div class="deltaTime">${esc(fmtDateTime(d.happened_at))}</div><div><div class="chipRow"><span class="contextChip">${esc(p?.name||'No Job')}</span><span class="sourceBadge compact">${esc(human(d.source_system))}</span>${d.meaningful?'<span class="meaningfulFlag">Meaningful</span>':''}</div><strong>${esc(d.summary||human(d.delta_type))}</strong>${d.meaningful_reason?`<p>${esc(d.meaningful_reason)}</p>`:''}</div></article>`}
function searchResult(r){return `<article class="brainSearchResult"><div class="resultType">${esc(resultTypeLabel(r.type))}</div><div><strong>${esc(r.title)}</strong>${r.subtitle?`<span>${esc(r.subtitle)}</span>`:''}</div><div class="resultScore">${r.score}</div><div class="rowActions">${r.type==='work'?`<button class="btn small primary" data-search-work="${esc(r.id)}">Manage</button>`:''}${r.type==='schedule'?`<button class="btn small secondary" data-search-schedule="${esc(r.id)}">Open</button>`:''}${r.type==='topic'?`<button class="btn small secondary" data-search-topic="${esc(r.id)}">Open</button>`:''}${r.url?`<a class="btn small secondary" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Original</a>`:''}</div></article>`}

function openTopicModal(id,state){const t=(state.raw.topics??[]).find(x=>x.id===id);if(!t)return;const links=(state.raw.topicSources??[]).filter(x=>x.topic_id===id),sources=links.map(l=>{const s=(state.raw.sourceRecords??[]).find(x=>x.id===l.source_record_id);if(!s)return null;const intel=state.intelligenceRecords.find(r=>r.sourceRecordId===s.id);return intel?.primarySource||{...s,isPrimary:l.relation==='primary',badge:human(s.source_system),actionLabel:'Open Original',resolvedUrl:s.source_url}}).filter(Boolean);openModal(`<div class="modalHeader"><div><div class="eyebrow">PROJECT TOPIC</div><h2>${esc(t.title)}</h2></div><button class="iconBtn" data-close-modal>×</button></div><div class="topicSummary"><p>${esc(t.summary||'')}</p><div class="chipRow">${t.floor?`<span class="contextChip">${esc(t.floor)}</span>`:''}${t.system_name?`<span class="contextChip">${esc(t.system_name)}</span>`:''}${t.equipment?`<span class="contextChip">${esc(t.equipment)}</span>`:''}</div></div><div class="detailSection"><strong>Evidence</strong>${sourceList(sources)}</div>`,{wide:true})}

export function renderBrain(ctx,root){
  const state=ctx.store.get(),scope=state.projectScope,scopeKey=`brain:${scope}`;
  const seen=(state.raw.seenState??[]).find(x=>x.scope_key===scopeKey)?.last_seen_at||null;
  const allDeltas=(state.raw.sourceDeltas??[]).filter(d=>(scope==='all'||d.project_id===scope));
  const deltas=(seen?allDeltas.filter(d=>d.happened_at>seen):allDeltas).slice(0,20);
  const suggestions=(state.raw.actionSuggestions??[]).filter(s=>s.state==='pending'&&(scope==='all'||s.project_id===scope));
  const commitments=(state.raw.commitments??[]).filter(c=>c.status!=='resolved'&&(scope==='all'||c.project_id===scope));
  const topics=(state.raw.topics??[]).filter(t=>t.status!=='closed'&&(scope==='all'||t.project_id===scope)).slice(0,20);
  const health=sourceHealth(state);
  root.innerHTML=`<div class="pageHeader brainHeader"><div><div class="eyebrow">EASTERN AIR PROJECT BRAIN</div><h1>Command Center Brain</h1><p>Search what Eastern knows, see what changed, and surface the few things that actually need a human.</p></div></div><section class="brainSearchHero"><label for="brainQuery">Search everything</label><div class="brainSearchBox"><input id="brainQuery" placeholder="Try: cooling tower, 4F piping, MAU release, Dan penetrations…"><button class="btn primary" id="brainSearchBtn">Search</button></div><div id="brainSearchResults"></div></section><section class="pageSection"><div class="sectionHeading"><div><h2>Source Health</h2><p>What the brain actually knows and how fresh each connected source is.</p></div></div><div class="brainHealthGrid">${health.map(healthCard).join('')||'<div class="emptyState">No source configs.</div>'}</div></section><div class="twoCol brainCols"><section class="pageSection"><div class="sectionHeading"><div><h2>Suggested Actions</h2><p>Evidence-backed things the brain thinks may need a human.</p></div><span class="countBubble">${suggestions.length}</span></div>${suggestions.map(s=>suggestionCard(s,state)).join('')||'<div class="emptyState">No pending suggestions.</div>'}</section><section class="pageSection"><div class="sectionHeading"><div><h2>Commitments / Waiting On</h2><p>Who owes what, based on captured evidence.</p></div><span class="countBubble">${commitments.length}</span></div>${commitments.map(c=>commitmentCard(c,state)).join('')||'<div class="emptyState">No open commitments.</div>'}</section></div><section class="pageSection"><div class="sectionHeading"><div><h2>${seen?'Since Last Visit':'Recent Source Changes'}</h2><p>${seen?`Since ${esc(fmtDateTime(seen))}`:'The delta engine will grow automatically as hourly syncs run.'}</p></div><button class="btn secondary" data-go-changes>Open What Changed</button></div><div class="brainDeltaList">${deltas.map(d=>deltaCard(d,state)).join('')||'<div class="emptyState">No source deltas yet. The new hourly sync will populate this.</div>'}</div></section><section class="pageSection"><div class="sectionHeading"><div><h2>Project Topics</h2><p>One real-world issue can combine Asana, Gmail, schedule and files.</p></div></div><div class="brainTopicGrid">${topics.map(t=>topicCard(t,state)).join('')||'<div class="emptyState">No topics yet.</div>'}</div></section>`;

  const doSearch=()=>{const q=qs('#brainQuery',root).value.trim(),target=qs('#brainSearchResults',root);if(!q){target.innerHTML='';return}const results=searchBrain(state.brainDocuments,q,state.raw.entityAliases??[],{projectScope:scope,limit:80});target.innerHTML=`<div class="brainSearchCount">${results.length} result${results.length===1?'':'s'}</div><div class="brainSearchList">${results.map(searchResult).join('')||'<div class="emptyState">Nothing matched across actions, sources, topics, commitments or schedule.</div>'}</div>`;wireSearchResults(target)};
  const wireSearchResults=target=>{qsa('[data-search-work]',target).forEach(b=>b.onclick=()=>ctx.openItem(b.dataset.searchWork));qsa('[data-search-schedule]',target).forEach(b=>b.onclick=()=>ctx.openSchedule(b.dataset.searchSchedule));qsa('[data-search-topic]',target).forEach(b=>b.onclick=()=>openTopicModal(b.dataset.searchTopic,state))};
  qs('#brainSearchBtn',root).onclick=doSearch;qs('#brainQuery',root).addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});
  qsa('[data-accept-suggestion]',root).forEach(b=>b.onclick=async()=>{const r=await ctx.api.acceptSuggestion(b.dataset.acceptSuggestion,state.user.id);if(r.error)return toast(r.error.message,{bad:true});toast('Added to My Work');await ctx.reload()});
  qsa('[data-dismiss-suggestion]',root).forEach(b=>b.onclick=async()=>{const r=await ctx.api.dismissSuggestion(b.dataset.dismissSuggestion,state.user.id);if(r.error)return toast(r.error.message,{bad:true});toast('Suggestion dismissed');await ctx.reload()});
  qsa('[data-resolve-commitment]',root).forEach(b=>b.onclick=async()=>{const r=await ctx.api.updateCommitmentStatus(b.dataset.resolveCommitment,'resolved');if(r.error)return toast(r.error.message,{bad:true});toast('Commitment resolved');await ctx.reload()});
  qsa('[data-open-topic]',root).forEach(b=>b.onclick=()=>openTopicModal(b.dataset.openTopic,state));qs('[data-go-changes]',root).onclick=()=>ctx.navigate('changes');
  ctx.api.markSeen(state.user.id,scopeKey).catch(()=>{});
}
