import { filterRecords } from '../core/filter-engine.mjs';
import { groupCycleByFloor, isCalculatedMilestone, isScheduleRisk, selectUpcoming } from '../core/schedule-engine.mjs';
import { esc, fmtDate, human, qs, qsa, todayIso } from '../ui/dom.mjs';
import { renderToolbar, wireToolbar, SCHEDULE_FILTER_DIMS } from '../ui/page-tools.mjs';

function filterShape(m){return {...m,scheduleCategory:m.category,source:m.sourceSystem?[m.sourceSystem]:[],attention:isScheduleRisk(m,todayIso())?'risk':'background'};}
function confidence(m){return `<span class="confidence ${esc(m.confidence)}">${esc(human(m.confidence))}</span>`}
function milestoneRow(m){return `<button class="milestoneRow ${isScheduleRisk(m,todayIso())?'risk':''}" data-milestone-id="${esc(m.id)}"><div class="milestoneDate">${m.plannedDate?esc(fmtDate(m.plannedDate)):'TBD'}</div><div class="milestoneMain"><strong>${esc(m.title)}</strong><span>${esc(m.projectName||'')}${m.floor?` · ${esc(m.floor)}`:''}${m.category?` · ${esc(human(m.category))}`:''}</span>${m.notes?`<small>${esc(m.notes)}</small>`:''}</div><div class="milestoneRight">${confidence(m)}<span class="statusChip ${esc(m.status)}">${esc(human(m.status))}</span></div></button>`}

function currentList(state){
  const scoped=state.schedule.filter(m=>state.projectScope==='all'||m.project===state.projectScope).map(filterShape);
  return filterRecords(scoped,state.viewState.filters,state.scheduleUniverse);
}

function monthView(state,list){
  const cursor=state.calendarCursor?new Date(`${state.calendarCursor}T12:00:00`):new Date();const y=cursor.getFullYear(),mo=cursor.getMonth(),first=new Date(y,mo,1),last=new Date(y,mo+1,0),start=new Date(first);start.setDate(1-first.getDay());const end=new Date(last);end.setDate(last.getDate()+(6-last.getDay()));
  let cells='';for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const key=d.toLocaleDateString('en-CA'),events=list.filter(m=>m.plannedDate===key),outside=d.getMonth()!==mo;cells+=`<button class="calendarDay ${outside?'outside':''} ${key===todayIso()?'today':''}" data-calendar-date="${key}"><span class="dayNumber">${d.getDate()}</span>${events.slice(0,3).map(e=>`<span class="calendarEvent ${isScheduleRisk(e,todayIso())?'risk':''}">${esc(e.title)}</span>`).join('')}${events.length>3?`<span class="moreEvents">+${events.length-3}</span>`:''}</button>`}
  return `<div class="calendarMonthHead"><button class="btn secondary small" data-cal-prev>‹</button><h2>${esc(first.toLocaleDateString([],{month:'long',year:'numeric'}))}</h2><button class="btn secondary small" data-cal-next>›</button><button class="btn secondary small" data-cal-today>Today</button></div><div class="weekHead"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendarGrid">${cells}</div>`;
}

function upcomingView(state,list,days=30){const rows=selectUpcoming(list,{today:todayIso(),days,projectScope:'all'});return `<div class="resultBar"><strong>${rows.length}</strong> milestone${rows.length===1?'':'s'} in the next ${days} days</div><div class="milestoneList">${rows.map(milestoneRow).join('')||'<div class="emptyState">No dated milestones match this view.</div>'}</div>`}
function lookaheadView(state,list){const rows=selectUpcoming(list,{today:todayIso(),days:21,projectScope:'all'}),byDate=new Map();for(const m of rows){if(!byDate.has(m.plannedDate))byDate.set(m.plannedDate,[]);byDate.get(m.plannedDate).push(m)}return `<div class="lookaheadGrid">${[...byDate].map(([date,items])=>`<section class="lookaheadDay"><div class="lookaheadDate"><strong>${esc(new Date(`${date}T12:00:00`).toLocaleDateString([],{weekday:'short'}))}</strong><span>${esc(fmtDate(date))}</span></div><div class="milestoneList">${items.map(milestoneRow).join('')}</div></section>`).join('')||'<div class="emptyState">Nothing in the next 21 days.</div>'}</div>`}
function cycleView(state,list){const groups=groupCycleByFloor(list,state.projectScope);return `<div class="cycleLegend"><span>Floor-by-floor Eastern cycle</span><span>${[...groups.values()].reduce((n,a)=>n+a.length,0)} cycle milestones</span></div>${[...groups].map(([floor,rows])=>`<section class="cycleFloor"><div class="cycleFloorHead"><h2>${esc(floor)}</h2><span>${rows.length} milestones</span></div><div class="cycleLane">${rows.map(m=>`<button class="cycleMilestone ${isScheduleRisk(m,todayIso())?'risk':''}" data-milestone-id="${esc(m.id)}"><span>${m.plannedDate?esc(fmtDate(m.plannedDate)):'TBD'}</span><strong>${esc(m.title)}</strong><small>${esc(human(m.status))} · ${esc(human(m.confidence))}</small></button>`).join('')}</div></section>`).join('')||'<div class="emptyState">No project-cycle milestones in this scope.</div>'}`}
function procurementView(state,list){const rows=list.filter(m=>m.category==='procurement'||['procurement_release','ship','delivery','calculated_lead_time'].includes(m.dateType)).sort((a,b)=>(a.plannedDate||'9999').localeCompare(b.plannedDate||'9999'));return `<div class="procurementNote">Procurement dates remain separate from GC/master schedule dates. Calculated lead-time dates are labeled CALCULATED.</div><div class="milestoneList">${rows.map(m=>milestoneRow(m).replace('</div></button>',`${isCalculatedMilestone(m)?'<span class="calcFlag">CALCULATED</span>':''}</div></button>`)).join('')||'<div class="emptyState">No procurement milestones match this view.</div>'}</div>`}

export function renderCalendar(ctx,root){
  const state=ctx.store.get(),mode=state.calendarMode||'month',list=currentList(state);
  let body='';if(mode==='month')body=monthView(state,list);if(mode==='lookahead')body=lookaheadView(state,list);if(mode==='upcoming')body=upcomingView(state,list,30);if(mode==='cycle')body=cycleView(state,list);if(mode==='procurement')body=procurementView(state,list);
  root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">${state.projectScope==='all'?'ALL JOBS':esc(state.maps.projects[state.projectScope]?.name||state.projectScope)}</div><h1>Calendar & Schedule</h1><p>Project-cycle dates, lookahead milestones and long-lead commitments with source confidence visible.</p></div></div>${renderToolbar(state,{page:'calendar',placeholder:'Search schedule, floor, activity…',dimensions:SCHEDULE_FILTER_DIMS,showSave:true})}<div class="modeBar">${[['month','Month'],['lookahead','Lookahead'],['upcoming','Upcoming'],['cycle','Project Cycle'],['procurement','Procurement / Long Lead']].map(([k,l])=>`<button class="modeChip ${mode===k?'active':''}" data-cal-mode="${k}">${l}</button>`).join('')}</div><div class="calendarBody">${body}</div>`;
  wireToolbar({root,state,store:ctx.store,api:ctx.api,page:'calendar',dimensions:SCHEDULE_FILTER_DIMS,onChange:ctx.render});qsa('[data-cal-mode]',root).forEach(b=>b.addEventListener('click',()=>{ctx.store.set({calendarMode:b.dataset.calMode});ctx.render()}));qsa('[data-milestone-id]',root).forEach(b=>b.addEventListener('click',()=>ctx.openSchedule(b.dataset.milestoneId)));qsa('[data-calendar-date]',root).forEach(b=>b.addEventListener('click',()=>ctx.openScheduleDay(b.dataset.calendarDate,list.filter(m=>m.plannedDate===b.dataset.calendarDate))));
  if(mode==='month'){const cursor=state.calendarCursor?new Date(`${state.calendarCursor}T12:00:00`):new Date();qs('[data-cal-prev]',root)?.addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()-1,1);ctx.store.set({calendarCursor:cursor.toLocaleDateString('en-CA')});ctx.render()});qs('[data-cal-next]',root)?.addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()+1,1);ctx.store.set({calendarCursor:cursor.toLocaleDateString('en-CA')});ctx.render()});qs('[data-cal-today]',root)?.addEventListener('click',()=>{ctx.store.set({calendarCursor:todayIso()});ctx.render()})}
}
