import {esc,fmtDate,human} from '../ui/dom.mjs';
import {resolveSourceLink} from '../core/source-links.mjs';

function stageOf(p){const s=String(p.submittal_status||'').toLowerCase();if(p.installed)return'installed';if(p.delivered)return'delivered';if(p.released_on||p.release_text)return'released';if(s.includes('approved')||s.includes('record'))return'approved';return'submittal'}
function riskOf(p,today){if(p.delivered||p.installed)return'good';if(p.expected_on&&p.expected_on<today)return'risk';if(/need|too long|awaiting|returned revise|resubmit|resubmitted/i.test(`${p.notes||''} ${p.submittal_status||''}`))return'watch';if(stageOf(p)==='approved'&&!p.released_on&&!p.release_text)return'watch';return'normal'}
function stageLabel(s){return({submittal:'Needs Submittal / Revise',approved:'Approved / Release Needed',released:'Released / Expected',delivered:'Delivered',installed:'Installed'})[s]||human(s)}
function sourceUrl(p,state){const s=(state.raw.sourceRecords??[]).find(x=>x.id===p.source_record_id);return s?resolveSourceLink(s).url:null}
function procCard(p,state,today){const stage=stageOf(p),risk=riskOf(p,today),url=sourceUrl(p,state);return`<article class="procCard ${risk}"><div class="procHead"><div><strong>${esc(p.unit_tag||p.equipment_description||p.source_key)}</strong><span>${esc(p.equipment_description||'')}</span></div><span class="procStage ${stage}">${esc(stageLabel(stage))}</span></div><div class="procMeta"><span>${esc(p.manufacturer||'Manufacturer —')}</span><span>${esc(p.rep||'Rep —')}</span>${p.lead_time_text?`<span>${esc(p.lead_time_text)}</span>`:''}</div><div class="procDates">${p.released_on?`<div><span>Released</span><strong>${esc(fmtDate(p.released_on))}</strong></div>`:''}${p.expected_on?`<div><span>Expected</span><strong class="${risk==='risk'?'badText':''}">${esc(fmtDate(p.expected_on))}</strong></div>`:''}${p.required_on?`<div><span>Required</span><strong>${esc(fmtDate(p.required_on))}</strong></div>`:''}</div><div class="chipRow"><span class="contextChip">${esc(p.submittal_status||'No submittal status')}</span><span class="confidence ${esc(p.confidence)}">${esc(human(p.confidence))}</span>${risk==='risk'?'<span class="attentionBadge risk">Past Expected</span>':risk==='watch'?'<span class="attentionBadge waiting">Needs Attention</span>':''}</div>${p.notes?`<p>${esc(p.notes)}</p>`:''}${url?`<a class="btn secondary small" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open Tracker</a>`:''}</article>`}
function stats(items,today){return{total:items.length,releaseUnknown:items.filter(p=>stageOf(p)==='approved'&&!p.released_on&&!p.release_text).length,overdue:items.filter(p=>riskOf(p,today)==='risk').length,watch:items.filter(p=>riskOf(p,today)==='watch').length,delivered:items.filter(p=>p.delivered).length}}

export function renderProcurement(ctx,root){const state=ctx.store.get(),today=new Date().toLocaleDateString('en-CA'),items=(state.raw.procurementItems??[]).filter(p=>state.projectScope==='all'||p.project_id===state.projectScope),summary=stats(items,today),stages=['submittal','approved','released','delivered','installed'];root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">PROCUREMENT / LONG LEAD</div><h1>Procurement Radar</h1><p>Major equipment lifecycle from the Eastern tracking logs, with release gaps and expected-date risk visible. Calculated dates stay labeled as calculated.</p></div></div><div class="metricGrid"><div class="metric"><strong>${summary.total}</strong><span>Major Packages</span></div><div class="metric"><strong>${summary.releaseUnknown}</strong><span>Approved / Release Unknown</span></div><div class="metric"><strong class="${summary.overdue?'badText':''}">${summary.overdue}</strong><span>Past Expected / Not Delivered</span></div><div class="metric"><strong>${summary.delivered}</strong><span>Delivered</span></div></div><div class="procBoard">${stages.map(stage=>{const rows=items.filter(p=>stageOf(p)===stage).sort((a,b)=>String(a.expected_on||'9999').localeCompare(String(b.expected_on||'9999')));return`<section class="procColumn"><div class="procColumnHead"><strong>${esc(stageLabel(stage))}</strong><span>${rows.length}</span></div><div class="procCards">${rows.map(p=>procCard(p,state,today)).join('')||'<div class="emptyInline">None</div>'}</div></section>`}).join('')}</div>`}
