import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://jgkucychrtbbeqscpwob.supabase.co';
const SUPABASE_KEY='sb_publishable_3nrRYH8KgwUXcQEpjGSMHw_Z3px-tYz';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const W='eastern-air';
const STATUS=['inbox','assigned','watching','working','waiting','follow_up','needs_review','snoozed','done'];
const PRIORITY=['critical','high','medium','low'];
let user=null,member=null,D={},page='today',projectFilter='all',scheduleWindow='30';
let filterState={search:'',people:[],categories:[],statuses:[],priorities:[],sources:[],showDone:false};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const fmt=d=>{if(!d)return'';const x=new Date(d+(/T/.test(d)?'':'T12:00:00'));return x.toLocaleDateString([], {month:'short',day:'numeric'})};
const today=()=>new Date().toLocaleDateString('en-CA');
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toLocaleDateString('en-CA')};

async function init(){const {data}=await sb.auth.getSession();user=data.session?.user||null;user?await enter():renderAuth();}
sb.auth.onAuthStateChange((e,s)=>{const nu=s?.user||null;if((nu?.id||null)!==(user?.id||null)){user=nu;setTimeout(()=>user?enter():renderAuth(),0)}});

function renderAuth(){document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="auth"><div class="authCard"><div class="brand"><div class="brandMark">EA</div><div><div class="brandTitle">Eastern Air</div><div class="brandSub">COMMAND CENTER</div></div></div><h1>Sign in</h1><p class="muted">One private management layer above your project systems.</p><div id="notice"></div><label>Name</label><input id="name" placeholder="Your name"><label>Email</label><input id="email" type="email"><label>Password</label><input id="pass" type="password"><div class="row" style="margin-top:14px"><button id="login" class="btn primary grow">Sign in</button><button id="signup" class="btn grow">Create account</button></div></div></div>`;$('#login').onclick=login;$('#signup').onclick=signup;}
function notice(t,bad=false){const n=$('#notice');if(!n)return;n.className='notice'+(bad?' error':'');n.textContent=t;}
async function login(){const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#pass').value});if(error)notice(error.message,true)}
async function signup(){const {data,error}=await sb.auth.signUp({email:$('#email').value.trim(),password:$('#pass').value,options:{data:{full_name:$('#name').value.trim()}}});if(error)return notice(error.message,true);if(!data.session)notice('Account created. Confirm your email, then sign in.');}
async function enter(){const {data}=await sb.from('workspace_members').select('role,active').eq('workspace_id',W).eq('user_id',user.id).maybeSingle();member=data;if(!member)return renderJoin();await load();restoreDefault();renderShell();}
function renderJoin(){const invite=new URLSearchParams(location.search).get('invite')||'';document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="auth"><div class="authCard"><div class="brand"><div class="brandMark">EA</div><div><div class="brandTitle">Eastern Air</div><div class="brandSub">COMMAND CENTER</div></div></div><h1>Join Eastern Air</h1><p class="muted">Signed in as ${esc(user.email)}</p><div id="notice"></div><label>Invite code</label><input id="invite" value="${esc(invite)}"><button id="accept" class="btn primary" style="width:100%;margin-top:10px">Accept invite</button><button id="logout" class="btn" style="width:100%;margin-top:18px">Sign out</button></div></div>`;$('#accept').onclick=acceptInvite;$('#logout').onclick=()=>sb.auth.signOut();}
async function acceptInvite(){const {data,error}=await sb.rpc('accept_workspace_invite',{p_token:$('#invite').value.trim()});if(error||!data)return notice(error?.message||'Invite is invalid or expired.',true);location.href=location.pathname;}

async function load(){const qs=await Promise.all([
 sb.from('projects').select('*').eq('workspace_id',W).eq('active',true).order('sort_order'),
 sb.from('work_categories').select('*').eq('workspace_id',W).eq('active',true).order('sort_order'),
 sb.from('people').select('*').eq('workspace_id',W).eq('active',true).order('name'),
 sb.from('items').select('*').eq('workspace_id',W).eq('active',true).order('updated_at',{ascending:false}),
 sb.from('item_management').select('*').eq('workspace_id',W),
 sb.from('item_assignees').select('*'),
 sb.from('user_item_preferences').select('*').eq('user_id',user.id),
 sb.from('item_watchers').select('*').eq('user_id',user.id),
 sb.from('profiles').select('id,display_name,email'),
 sb.from('workspace_members').select('workspace_id,user_id,role,active').eq('workspace_id',W),
 sb.from('saved_views').select('*').eq('workspace_id',W).or(`owner_user_id.eq.${user.id},is_shared.eq.true`).order('sort_order'),
 sb.from('user_preferences').select('*').eq('user_id',user.id).eq('workspace_id',W).maybeSingle(),
 sb.from('schedule_milestones').select('*').eq('workspace_id',W).order('planned_date'),
 sb.from('item_sources').select('*'),
 sb.from('source_records').select('id,source_system,project_id,title,source_url,is_historical').eq('workspace_id',W)
]);
 D={projects:qs[0].data||[],categories:qs[1].data||[],people:qs[2].data||[],items:qs[3].data||[],mgmt:qs[4].data||[],assign:qs[5].data||[],prefs:qs[6].data||[],watchers:qs[7].data||[],profiles:qs[8].data||[],members:qs[9].data||[],views:qs[10].data||[],userPrefs:qs[11].data||null,schedule:qs[12].data||[],itemSources:qs[13].data||[],sources:qs[14].data||[]};
}
function maps(){return{p:Object.fromEntries(D.projects.map(x=>[x.id,x])),c:Object.fromEntries(D.categories.map(x=>[x.id,x])),m:Object.fromEntries(D.mgmt.map(x=>[x.item_id,x])),pref:Object.fromEntries(D.prefs.map(x=>[x.item_id,x])),src:Object.fromEntries(D.sources.map(x=>[x.id,x]))}}
function effective(i,M){const m=M.m[i.id]||{};return{project:m.project_id_override||i.project_id,category:m.category_id_override||i.category_id,title:m.title_override||i.title,priority:m.priority_override||i.priority,due:m.due_override||i.due_at,status:m.status||'inbox',follow:m.follow_up_at,note:m.shared_note,owner:m.current_owner_person_id,confidence:i.confidence||'source_says'}}
function ownerFor(id){const a=D.assign.find(x=>x.item_id===id&&x.active&&x.is_primary);return a?D.people.find(p=>p.id===a.person_id):null}
function sourceFor(id,M){const links=D.itemSources.filter(x=>x.item_id===id);return links.map(x=>M.src[x.source_record_id]?.source_system).filter(Boolean)}
function myPerson(){return D.people.find(x=>x.linked_user_id===user.id)}
function active(i,M){return effective(i,M).status!=='done'}
function currentScopeKey(){return `${projectFilter}|${page}`}
function defaultSettings(){return D.userPrefs?.settings?.defaults||{}}
function restoreDefault(){const saved=defaultSettings()[currentScopeKey()];filterState=saved?JSON.parse(JSON.stringify(saved)):{search:'',people:[],categories:[],statuses:[],priorities:[],sources:[],showDone:false};}
function filterCount(){return ['people','categories','statuses','priorities','sources'].reduce((n,k)=>n+(filterState[k]?.length||0),0)+(filterState.showDone?1:0)}
function filteredItems(base){const M=maps(),q=filterState.search.trim().toLowerCase();return base.filter(i=>{const e=effective(i,M),o=ownerFor(i.id),src=sourceFor(i.id,M);if(projectFilter!=='all'&&e.project!==projectFilter)return false;if(!filterState.showDone&&e.status==='done')return false;if(q&&!`${e.title} ${i.description||''} ${o?.name||''} ${M.p[e.project]?.name||''} ${M.c[e.category]?.name||''}`.toLowerCase().includes(q))return false;if(filterState.people.length&&(!o||!filterState.people.includes(o.id)))return false;if(filterState.categories.length&&!filterState.categories.includes(e.category))return false;if(filterState.statuses.length&&!filterState.statuses.includes(e.status))return false;if(filterState.priorities.length&&!filterState.priorities.includes(e.priority))return false;if(filterState.sources.length&&!src.some(s=>filterState.sources.includes(s)))return false;return true})}
function sourceIsPersonal(i,M){const src=sourceFor(i.id,M);return i.origin==='command_center'||src.includes('todoist')}
function liveMine(i,M){const e=effective(i,M),o=ownerFor(i.id),w=D.watchers.some(x=>x.item_id===i.id),pref=M.pref[i.id];if(pref?.dismissed_from_live)return false;if(e.status==='done')return false;if(o?.linked_user_id===user.id||w)return true;if(!o&&sourceIsPersonal(i,M)&&['inbox','working','waiting','follow_up','needs_review','watching'].includes(e.status))return true;return false}

function renderShell(){document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="shell"><header class="top"><div class="topIn"><div class="brandRow"><div class="brand"><div class="brandMark">EA</div><div><div class="brandTitle">Command Center</div><div class="brandSub">READ-ONLY SOURCES • EDITABLE MANAGEMENT</div></div></div><div class="userPill">${esc(user.email)} • ${esc(member.role)}</div></div><div id="projectChips" class="chips"></div></div></header><main id="main" class="main"></main><nav class="bottom"><div class="bottomIn">${[['today','⌂','Today'],['schedule','◷','Schedule'],['mine','✓','My Work'],['assigned','→','Assigned'],['jobs','▦','Jobs'],['team','♟','Team']].map(x=>`<button class="navBtn" data-page="${x[0]}"><span class="navIcon">${x[1]}</span>${x[2]}</button>`).join('')}</div></nav><div id="modalWrap" class="modalWrap"><div id="modal" class="modal"></div></div></div>`;renderProjectChips();$$('.navBtn').forEach(b=>b.onclick=()=>{page=b.dataset.page;restoreDefault();renderPage()});renderPage();}
function renderProjectChips(){const a=[`<button class="chip ${projectFilter==='all'?'active':''}" data-p="all">All Jobs</button>`].concat(D.projects.filter(x=>x.id!=='other-work').map(x=>`<button class="chip ${projectFilter===x.id?'active':''}" data-p="${x.id}">${esc(x.name.replace(' Street',''))}</button>`));$('#projectChips').innerHTML=a.join('');$$('#projectChips .chip').forEach(b=>b.onclick=()=>{projectFilter=b.dataset.p;restoreDefault();renderProjectChips();renderPage()});}
function head(title,sub,add=true){return `<div class="pageHead"><div><h1>${esc(title)}</h1><div class="muted">${esc(sub)}</div></div><div class="pageActions">${add?'<button class="btn primary" id="quickAdd">+ Add</button>':''}</div></div>`}
function toolbar(){const views=D.views.filter(v=>{const f=v.filters||{};return !f.project_id||f.project_id===projectFilter||projectFilter==='all'});return `<div class="toolbar"><div class="searchBox"><input id="workSearch" value="${esc(filterState.search)}" placeholder="Search title, notes, person, category…"></div><button class="btn filterBtn" id="openFilters">Filters${filterCount()?`<span class="filterCount">${filterCount()}</span>`:''}</button></div><div class="savedBar"><button class="chip view" id="clearView">All</button>${views.map(v=>`<button class="chip view savedView" data-id="${v.id}">#${esc(v.name)}</button>`).join('')}<button class="chip view" id="saveView">+ Save view</button></div>`}
function statusOptions(v){return STATUS.map(s=>`<option value="${s}" ${v===s?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}
function card(i,M){const e=effective(i,M),o=ownerFor(i.id),p=M.p[e.project],c=M.c[e.category],src=sourceFor(i.id,M),over=e.due&&e.due<today()&&e.status!=='done';return `<article class="card"><div class="cardTop"><div class="grow"><div class="title">${esc(e.title)}</div><div class="meta"><span class="pill">${esc(p?.name||'No job')}</span><span class="pill">${esc(c?.name||'General')}</span><span class="pill ${esc(e.priority)}">${esc(e.priority)}</span><span class="pill">${esc(o?.name||'Unassigned')}</span>${src.slice(0,1).map(s=>`<span class="pill source">${esc(s)}</span>`).join('')}</div></div><div class="due ${over?'over':''}">${esc(fmt(e.due))}</div></div><div class="cardActions"><select class="selectSmall statusQuick" data-id="${i.id}">${statusOptions(e.status)}</select><button class="btn small manage" data-id="${i.id}">Manage</button><button class="btn small commentBtn" data-id="${i.id}">Comment</button></div></article>`}
function kpis(arr,M){const overdue=arr.filter(i=>effective(i,M).due&&effective(i,M).due<today()&&active(i,M)).length,review=arr.filter(i=>effective(i,M).status==='needs_review').length,wait=arr.filter(i=>['waiting','follow_up'].includes(effective(i,M).status)).length,assigned=arr.filter(i=>ownerFor(i.id)).length;return `<div class="kpis"><div class="kpi"><strong>${overdue}</strong><span>OVERDUE</span></div><div class="kpi"><strong>${review}</strong><span>NEEDS REVIEW</span></div><div class="kpi"><strong>${wait}</strong><span>WAIT / FOLLOW-UP</span></div><div class="kpi"><strong>${assigned}</strong><span>ASSIGNED</span></div></div>`}
function wireCards(){$$('.manage').forEach(b=>b.onclick=()=>openManage(b.dataset.id,false));$$('.commentBtn').forEach(b=>b.onclick=()=>openManage(b.dataset.id,true));$$('.statusQuick').forEach(s=>s.onchange=()=>setStatus(s.dataset.id,s.value));}
function wireAdd(){if($('#quickAdd'))$('#quickAdd').onclick=openAdd}
function wireToolbar(){if($('#workSearch'))$('#workSearch').oninput=e=>{filterState.search=e.target.value;renderPage(false)};if($('#openFilters'))$('#openFilters').onclick=openFilters;if($('#clearView'))$('#clearView').onclick=()=>{filterState={search:'',people:[],categories:[],statuses:[],priorities:[],sources:[],showDone:false};renderPage()};$$('.savedView').forEach(b=>b.onclick=()=>applySavedView(b.dataset.id));if($('#saveView'))$('#saveView').onclick=openSaveView;}
function renderPage(resetScroll=true){$$('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='today')renderToday();if(page==='schedule')renderSchedule();if(page==='mine')renderMine();if(page==='assigned')renderAssigned();if(page==='jobs')renderJobs();if(page==='team')renderTeam();}
function renderToday(){const M=maps(),base=D.items.filter(i=>liveMine(i,M)),arr=filteredItems(base),focus=arr.filter(i=>{const e=effective(i,M);return ['inbox','needs_review'].includes(e.status)||(e.due&&e.due<=today())||(e.follow&&e.follow<=today())});const upcoming=scheduleSlice(14,6);$('#main').innerHTML=head('Today','What you need to know, do, review, or chase.')+toolbar()+kpis(arr,M)+`<div class="section"><div class="sectionTitle">Coming Up</div><div class="comingGrid">${upcoming.length?upcoming.map(scheduleMini).join(''):'<div class="empty">No dated milestones in this view.</div>'}</div></div><div class="section"><div class="sectionTitle">My Attention</div><div class="resultCount">${focus.length} item${focus.length===1?'':'s'}</div><div class="cards">${focus.length?focus.map(i=>card(i,M)).join(''):'<div class="empty">Nothing urgent in your live queue.</div>'}</div></div>`;wireAdd();wireToolbar();wireCards();}
function renderMine(){const M=maps(),base=D.items.filter(i=>liveMine(i,M)),arr=filteredItems(base);$('#main').innerHTML=head('My Work','Your actual management list — not every source record.')+toolbar()+kpis(arr,M)+`<div class="resultCount">${arr.length} item${arr.length===1?'':'s'} in this view</div><div class="cards">${arr.length?arr.map(i=>card(i,M)).join(''):'<div class="empty">No items match this view.</div>'}</div>`;wireAdd();wireToolbar();wireCards();}
function renderAssigned(){const M=maps(),me=myPerson(),base=D.items.filter(i=>active(i,M)&&ownerFor(i.id)&&ownerFor(i.id).id!==me?.id),arr=filteredItems(base);$('#main').innerHTML=head('Assigned Out','Everything owned by someone else — filter by person, job, category, status or source.')+toolbar()+`<div class="resultCount">${arr.length} item${arr.length===1?'':'s'}</div><div class="cards">${arr.length?arr.map(i=>card(i,M)).join(''):'<div class="empty">No assigned work matches this view.</div>'}</div>`;wireAdd();wireToolbar();wireCards();}
function renderJobs(){const M=maps(),jobs=D.projects.filter(p=>p.id!=='other-work'&&(projectFilter==='all'||p.id===projectFilter));$('#main').innerHTML=head('Jobs','Each job can have its own saved/default view.')+toolbar()+`<div class="jobGrid">${jobs.map(p=>{const a=filteredItems(D.items.filter(i=>effective(i,M).project===p.id&&active(i,M)));const next=D.schedule.filter(s=>s.project_id===p.id&&s.planned_date&&s.planned_date>=today()).sort((a,b)=>a.planned_date.localeCompare(b.planned_date))[0];return `<div class="jobCard"><div class="jobName">${esc(p.name)}</div><div class="jobStats"><div><b>${a.length}</b><span>MATCHING</span></div><div><b>${a.filter(i=>effective(i,M).status==='needs_review').length}</b><span>REVIEW</span></div><div><b>${a.filter(i=>ownerFor(i.id)).length}</b><span>ASSIGNED</span></div></div><div class="muted" style="margin-top:9px;font-size:11px">${next?`Next: ${fmt(next.planned_date)} — ${esc(next.title)}`:'No verified future date loaded'}</div><div class="row" style="margin-top:12px"><button class="btn small jobOpen" data-p="${p.id}">Open work</button><button class="btn small jobSchedule" data-p="${p.id}">Schedule</button></div></div>`}).join('')}</div>`;wireAdd();wireToolbar();$$('.jobOpen').forEach(b=>b.onclick=()=>{projectFilter=b.dataset.p;page='mine';restoreDefault();renderProjectChips();renderPage()});$$('.jobSchedule').forEach(b=>b.onclick=()=>{projectFilter=b.dataset.p;page='schedule';restoreDefault();renderProjectChips();renderPage()});}
function renderTeam(){const M=maps();$('#main').innerHTML=head('Team','Assign work to people even before they have a login.',false)+`<div class="row" style="margin-bottom:12px"><button class="btn" id="addPerson">+ Person</button>${member.role==='admin'?'<button class="btn primary" id="inviteUser">Invite login</button>':''}<button class="btn" id="logoutTop">Sign out</button></div>${D.people.map(p=>{const a=D.items.filter(i=>ownerFor(i.id)?.id===p.id&&active(i,M));return `<div class="personBlock"><div class="row"><div class="grow"><div class="personName">${esc(p.name)}</div><div class="personStats">${a.length} active • ${p.linked_user_id?'login connected':'no login yet'}</div></div><button class="btn small personOpen" data-person="${p.id}">View work</button></div></div>`}).join('')}`;$('#logoutTop').onclick=()=>sb.auth.signOut();$('#addPerson').onclick=openAddPerson;if($('#inviteUser'))$('#inviteUser').onclick=openInvite;$$('.personOpen').forEach(b=>b.onclick=()=>{filterState.people=[b.dataset.person];page='assigned';renderPage()});}

function scheduleSlice(days=30,limit=999){const end=addDays(today(),days);return D.schedule.filter(s=>(projectFilter==='all'||s.project_id===projectFilter)&&s.planned_date&&s.planned_date>=today()&&s.planned_date<=end&&(!filterState.search||`${s.title} ${s.floor||''} ${s.category||''} ${s.notes||''}`.toLowerCase().includes(filterState.search.toLowerCase()))).sort((a,b)=>a.planned_date.localeCompare(b.planned_date)).slice(0,limit)}
function scheduleMini(s){const p=D.projects.find(x=>x.id===s.project_id);return `<div class="comingItem"><div class="comingDate">${fmt(s.planned_date)}</div><div><div class="comingTitle">${esc(s.title)}</div><div class="comingSub">${esc(p?.name||'')} ${s.floor?`• ${esc(s.floor)}`:''} • ${esc(s.confidence?.replaceAll('_',' ')||'source says')}</div></div></div>`}
function scheduleRow(s){const p=D.projects.find(x=>x.id===s.project_id);return `<div class="scheduleRow ${s.status==='at_risk'||s.status==='delayed'?'scheduleNeed':''}"><div class="scheduleDate">${s.planned_date?fmt(s.planned_date):'TBD'}</div><div><div class="scheduleTitle">${esc(s.title)}</div><div class="scheduleMeta"><span class="pill">${esc(p?.name||'')}</span>${s.floor?`<span class="pill">${esc(s.floor)}</span>`:''}${s.category?`<span class="pill">${esc(s.category)}</span>`:''}<span class="pill ${s.confidence==='needs_verification'?'verify':'confirmed'}">${esc((s.confidence||'source_says').replaceAll('_',' '))}</span><span class="pill">${esc(s.status)}</span></div>${s.notes?`<div class="muted" style="font-size:11px;margin-top:6px">${esc(s.notes)}</div>`:''}</div></div>`}
function renderSchedule(){const q=filterState.search.toLowerCase(),end=scheduleWindow==='all'?null:addDays(today(),Number(scheduleWindow));let rows=D.schedule.filter(s=>(projectFilter==='all'||s.project_id===projectFilter)&&(!q||`${s.title} ${s.floor||''} ${s.category||''} ${s.notes||''}`.toLowerCase().includes(q)));if(scheduleWindow!=='all')rows=rows.filter(s=>s.planned_date&&s.planned_date>=today()&&s.planned_date<=end);rows.sort((a,b)=>(a.planned_date||'9999').localeCompare(b.planned_date||'9999'));$('#main').innerHTML=head('Schedule','Upcoming project milestones with source confidence kept visible.',false)+`<div class="toolbar"><div class="searchBox"><input id="workSearch" value="${esc(filterState.search)}" placeholder="Search schedule, floor, system…"></div><button class="btn filterBtn" id="openFilters">Filters${filterCount()?`<span class="filterCount">${filterCount()}</span>`:''}</button></div><div class="scheduleControls">${[['14','2 weeks'],['30','30 days'],['90','90 days'],['all','All']].map(x=>`<button class="chip ${scheduleWindow===x[0]?'active':''}" data-win="${x[0]}">${x[1]}</button>`).join('')}</div><div class="resultCount">${rows.length} milestone${rows.length===1?'':'s'}</div>${rows.length?rows.map(scheduleRow).join(''):'<div class="empty">No dated schedule items match this view.</div>'}`;$('#workSearch').oninput=e=>{filterState.search=e.target.value;renderSchedule()};$('#openFilters').onclick=openFilters;$$('[data-win]').forEach(b=>b.onclick=()=>{scheduleWindow=b.dataset.win;renderSchedule()});}

function openFilters(){const personChecks=D.people.map(p=>`<label class="checkItem"><input type="checkbox" data-filter="people" value="${p.id}" ${filterState.people.includes(p.id)?'checked':''}>${esc(p.name)}</label>`).join('');const catChecks=D.categories.map(c=>`<label class="checkItem"><input type="checkbox" data-filter="categories" value="${c.id}" ${filterState.categories.includes(c.id)?'checked':''}>${esc(c.name)}</label>`).join('');const statusChecks=STATUS.map(s=>`<label class="checkItem"><input type="checkbox" data-filter="statuses" value="${s}" ${filterState.statuses.includes(s)?'checked':''}>${s.replaceAll('_',' ')}</label>`).join('');const priChecks=PRIORITY.map(s=>`<label class="checkItem"><input type="checkbox" data-filter="priorities" value="${s}" ${filterState.priorities.includes(s)?'checked':''}>${s}</label>`).join('');const sources=['asana','gmail','todoist','file','command_center'].map(s=>`<label class="checkItem"><input type="checkbox" data-filter="sources" value="${s}" ${filterState.sources.includes(s)?'checked':''}>${s}</label>`).join('');openModal(`<div class="modalHead"><div><h2>Filters</h2><div class="muted">These apply to ${projectFilter==='all'?'all jobs':D.projects.find(p=>p.id===projectFilter)?.name||projectFilter}.</div></div><button class="close" id="closeModal">×</button></div><div class="filterGrid"><div class="filterGroup"><div class="filterGroupTitle">People</div><div class="checkList">${personChecks}</div></div><div class="filterGroup"><div class="filterGroupTitle">Category</div><div class="checkList">${catChecks}</div></div><div class="filterGroup"><div class="filterGroupTitle">Status</div><div class="checkList">${statusChecks}</div></div><div class="filterGroup"><div class="filterGroupTitle">Priority</div><div class="checkList">${priChecks}</div></div><div class="filterGroup"><div class="filterGroupTitle">Source</div><div class="checkList">${sources}</div></div><div class="filterGroup"><div class="filterGroupTitle">Other</div><label class="checkItem"><input id="fShowDone" type="checkbox" ${filterState.showDone?'checked':''}>Include Done</label></div></div><div class="filterFooter"><button class="btn grow" id="resetFilters">Reset</button><button class="btn grow" id="setDefault">Set default for this job</button><button class="btn primary grow" id="applyFilters">Apply</button></div>`);$('#resetFilters').onclick=()=>{filterState={search:filterState.search,people:[],categories:[],statuses:[],priorities:[],sources:[],showDone:false};closeModal();renderPage()};$('#applyFilters').onclick=()=>{readFilterModal();closeModal();renderPage()};$('#setDefault').onclick=async()=>{readFilterModal();await saveDefault();closeModal();renderPage()};}
function readFilterModal(){['people','categories','statuses','priorities','sources'].forEach(k=>filterState[k]=$$(`input[data-filter="${k}"]:checked`).map(x=>x.value));filterState.showDone=$('#fShowDone')?.checked||false;}
async function saveDefault(){const settings=D.userPrefs?.settings||{};settings.defaults=settings.defaults||{};settings.defaults[currentScopeKey()]=JSON.parse(JSON.stringify(filterState));const row={user_id:user.id,workspace_id:W,settings,updated_at:new Date().toISOString()};const {error}=await sb.from('user_preferences').upsert(row,{onConflict:'user_id'});if(error)return alert(error.message);D.userPrefs=row;}
function openSaveView(){openModal(`<div class="modalHead"><h2>Save View</h2><button class="close" id="closeModal">×</button></div><label>View name</label><input id="viewName" placeholder="YosefToday"><label class="toggleline"><input type="checkbox" id="viewShared">Shared with the team</label><p class="muted">The saved view remembers this job, page and all current filters.</p><button class="btn primary" id="saveViewNow" style="width:100%">Save view</button>`);$('#saveViewNow').onclick=saveViewNow;}
async function saveViewNow(){const name=$('#viewName').value.trim().replace(/^#/,'');if(!name)return alert('Give the view a name.');const filters={...filterState,project_id:projectFilter,page};const row={workspace_id:W,owner_user_id:user.id,name,is_shared:$('#viewShared').checked,filters,sort_order:D.views.length+1,updated_at:new Date().toISOString()};const {error}=await sb.from('saved_views').insert(row);if(error)return alert(error.message);closeModal();await reload();}
function applySavedView(id){const v=D.views.find(x=>x.id===id);if(!v)return;const f=v.filters||{};projectFilter=f.project_id||projectFilter;page=f.page||page;filterState={search:f.search||'',people:f.people||[],categories:f.categories||[],statuses:f.statuses||[],priorities:f.priorities||[],sources:f.sources||[],showDone:!!f.showDone};renderProjectChips();renderPage();}

async function setStatus(id,status){const old=D.mgmt.find(x=>x.item_id===id)||{};const row={...old,item_id:id,workspace_id:W,status,updated_by:user.id,updated_at:new Date().toISOString(),resolved_at:status==='done'?new Date().toISOString():null,resolved_by:status==='done'?user.id:null};const {error}=await sb.from('item_management').upsert(row,{onConflict:'item_id'});if(error)return alert(error.message);await reload();}
function openModal(html){$('#modal').innerHTML=html;$('#modalWrap').classList.add('open');$('#modalWrap').onclick=e=>{if(e.target.id==='modalWrap')closeModal()};if($('#closeModal'))$('#closeModal').onclick=closeModal}
function closeModal(){$('#modalWrap').classList.remove('open')}
const projectOptions=sel=>D.projects.map(p=>`<option value="${p.id}" ${sel===p.id?'selected':''}>${esc(p.name)}</option>`).join('');
const categoryOptions=sel=>D.categories.map(c=>`<option value="${c.id}" ${sel===c.id?'selected':''}>${esc(c.name)}</option>`).join('');
const peopleOptions=sel=>'<option value="">Unassigned</option>'+D.people.map(p=>`<option value="${p.id}" ${sel===p.id?'selected':''}>${esc(p.name)}</option>`).join('');
function openAdd(){openModal(`<div class="modalHead"><h2>Add Work</h2><button class="close" id="closeModal">×</button></div><label>What needs to happen?</label><input id="aTitle"><div class="formGrid"><div><label>Job</label><select id="aProject">${projectOptions(projectFilter==='all'?D.projects[0]?.id:projectFilter)}</select></div><div><label>Category</label><select id="aCategory">${categoryOptions('general')}</select></div><div><label>Priority</label><select id="aPriority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></div><div><label>Due</label><input id="aDue" type="date"></div></div><label>Assign to</label><select id="aOwner">${peopleOptions('')}</select><label>Notes</label><textarea id="aDesc"></textarea><button class="btn primary" id="saveAdd" style="width:100%;margin-top:14px">Add to Command Center</button>`);$('#saveAdd').onclick=saveAdd;}
async function saveAdd(){const category=$('#aCategory').value,row={workspace_id:W,project_id:$('#aProject').value,title:$('#aTitle').value.trim(),description:$('#aDesc').value.trim()||null,category_id:category,category,priority:$('#aPriority').value,due_at:$('#aDue').value||null,origin:'command_center',confidence:'confirmed',created_by:user.id};if(!row.title)return alert('Add a title.');const {data,error}=await sb.from('items').insert(row).select().single();if(error)return alert(error.message);await sb.from('item_management').insert({item_id:data.id,workspace_id:W,status:'inbox',updated_by:user.id});if($('#aOwner').value)await sb.rpc('assign_item',{p_item_id:data.id,p_person_id:$('#aOwner').value,p_note:'Assigned when created',p_keep_watching:false});closeModal();await reload();}
async function openManage(id,commentsOnly){const M=maps(),i=D.items.find(x=>x.id===id),e=effective(i,M),o=ownerFor(id);const {data:comments=[]}=await sb.from('item_comments').select('*').eq('item_id',id).order('created_at');const prof=Object.fromEntries(D.profiles.map(x=>[x.id,x]));openModal(`<div class="modalHead"><div class="grow"><div class="muted">${esc(M.p[e.project]?.name||'')}</div><h2>${esc(e.title)}</h2></div><button class="close" id="closeModal">×</button></div>${commentsOnly?'':`<div class="formGrid"><div><label>Job</label><select id="mProject">${projectOptions(e.project)}</select></div><div><label>Category</label><select id="mCategory">${categoryOptions(e.category)}</select></div><div><label>Status</label><select id="mStatus">${statusOptions(e.status)}</select></div><div><label>Priority</label><select id="mPriority">${['low','medium','high','critical'].map(s=>`<option ${e.priority===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label>Due</label><input id="mDue" type="date" value="${esc(e.due||'')}"></div><div><label>Follow up</label><input id="mFollow" type="date" value="${esc(e.follow||'')}"></div></div><label>Assign / hand off to</label><select id="mOwner">${peopleOptions(o?.id||'')}</select><label>Shared note</label><textarea id="mNote">${esc(e.note||'')}</textarea><label class="toggleline"><input id="mWatch" type="checkbox" ${D.watchers.some(x=>x.item_id===id)?'checked':''}>Keep this in my live view after assigning it to someone else</label><div class="row" style="margin-top:12px"><button class="btn primary grow" id="saveManage">Save</button><button class="btn grow" id="dismissMine">Remove from my live view</button></div><hr style="border:0;border-top:1px solid var(--line);margin:20px 0">`}<div class="sectionTitle">Conversation</div>${comments.length?comments.map(c=>`<div class="comment"><div class="commentName">${esc(prof[c.author_user_id]?.display_name||prof[c.author_user_id]?.email||'Team')} • ${fmt(c.created_at)}</div><div class="commentBody">${esc(c.body)}</div></div>`).join(''):'<div class="muted">No comments yet.</div>'}<label>Add comment</label><textarea id="newComment"></textarea><button class="btn" id="sendComment" style="width:100%">Post comment</button>`);if(!commentsOnly){$('#saveManage').onclick=()=>saveManage(id,o?.id||'');$('#dismissMine').onclick=()=>dismissMine(id)}$('#sendComment').onclick=()=>postComment(id);}
async function saveManage(id,oldOwner){const old=D.mgmt.find(x=>x.item_id===id)||{},status=$('#mStatus').value,row={...old,item_id:id,workspace_id:W,status,project_id_override:$('#mProject').value,category_id_override:$('#mCategory').value,priority_override:$('#mPriority').value,due_override:$('#mDue').value||null,follow_up_at:$('#mFollow').value||null,shared_note:$('#mNote').value.trim()||null,updated_by:user.id,updated_at:new Date().toISOString(),resolved_at:status==='done'?new Date().toISOString():null,resolved_by:status==='done'?user.id:null};const {error}=await sb.from('item_management').upsert(row,{onConflict:'item_id'});if(error)return alert(error.message);const owner=$('#mOwner').value;if(owner&&owner!==oldOwner){const r=await sb.rpc('assign_item',{p_item_id:id,p_person_id:owner,p_note:$('#mNote').value.trim()||null,p_keep_watching:$('#mWatch').checked});if(r.error)return alert(r.error.message)}closeModal();await reload();}
async function dismissMine(id){const old=D.prefs.find(x=>x.item_id===id)||{};const {error}=await sb.from('user_item_preferences').upsert({...old,user_id:user.id,item_id:id,dismissed_from_live:true,updated_at:new Date().toISOString()},{onConflict:'user_id,item_id'});if(error)return alert(error.message);closeModal();await reload();}
async function postComment(id){const body=$('#newComment').value.trim();if(!body)return;const {error}=await sb.from('item_comments').insert({workspace_id:W,item_id:id,author_user_id:user.id,body});if(error)return alert(error.message);await load();openManage(id,true);}
function openAddPerson(){openModal(`<div class="modalHead"><h2>Add Person</h2><button class="close" id="closeModal">×</button></div><label>Name</label><input id="pName"><label>Email (optional)</label><input id="pEmail" type="email"><p class="muted">Assign work before they have a login. Their future login can attach to the same person.</p><button class="btn primary" id="savePerson" style="width:100%">Add person</button>`);$('#savePerson').onclick=savePerson;}
async function savePerson(){const name=$('#pName').value.trim(),email=$('#pEmail').value.trim()||null;if(!name)return alert('Name is required.');const {error}=await sb.from('people').insert({workspace_id:W,name,email,source_kind:'command_center'});if(error)return alert(error.message);closeModal();await reload();}
function openInvite(){openModal(`<div class="modalHead"><h2>Invite Login</h2><button class="close" id="closeModal">×</button></div><label>Email</label><input id="iEmail" type="email"><label>Role</label><select id="iRole"><option value="member">Member — manage work</option><option value="viewer">Viewer — read only</option><option value="manager">Manager</option><option value="admin">Admin</option></select><button class="btn primary" id="makeInvite" style="width:100%;margin-top:14px">Create private invite link</button><div id="inviteResult"></div>`);$('#makeInvite').onclick=makeInvite;}
async function makeInvite(){const {data,error}=await sb.rpc('create_workspace_invite',{p_email:$('#iEmail').value.trim(),p_role:$('#iRole').value,p_expires_days:7});if(error)return alert(error.message);const link=location.origin+location.pathname+'?invite='+encodeURIComponent(data);$('#inviteResult').innerHTML=`<label>Invite link</label><textarea id="inviteLink" readonly>${esc(link)}</textarea><button class="btn" id="copyInvite" style="width:100%">Copy link</button>`;$('#copyInvite').onclick=async()=>{await navigator.clipboard.writeText(link);$('#copyInvite').textContent='Copied'};}
async function reload(){await load();renderProjectChips();renderPage();}
init();
