import { MISSING } from '../core/filter-engine.mjs';
import { resolveSourceLink, sourceActionLabel, sourceLabel } from '../core/source-links.mjs';
import { esc, fmtDateTime, human, qs, qsa, toast } from '../ui/dom.mjs';

function sourceRow(source,state){
  const resolved=resolveSourceLink(source),project=state.maps.projects[source.project_id],link=state.raw.itemSources.find(x=>x.source_record_id===source.id),item=link?state.records.find(r=>r.id===link.item_id):null;
  return `<article class="intelRow"><div class="intelTop"><div class="chipRow"><span class="sourceBadge">${esc(sourceLabel(source.source_system))}</span><span class="contextChip">${esc(project?.name||'No Job')}</span>${source.is_historical?'<span class="contextChip historical">Historical</span>':'<span class="contextChip current">Current</span>'}${item?`<span class="attentionBadge ${esc(item.attentionState)}">${esc(human(item.attentionState))}</span>`:''}</div><div class="rowActions">${resolved.url?`<a class="btn small secondary" href="${esc(resolved.url)}" target="_blank" rel="noopener noreferrer">${esc(sourceActionLabel(source.source_system))}</a>`:''}${item&&item.attentionState==='background'?`<button class="btn small primary" data-promote-item="${esc(item.id)}">Promote</button>`:''}${item&&item.attentionState!=='background'?`<button class="btn small primary" data-manage-item="${esc(item.id)}">Manage</button>`:''}</div></div><h3>${esc(source.title||'Untitled source')}</h3><div class="intelMeta">Source ID: ${esc(source.source_ref||'—')} ${source.source_updated_at?`· Updated ${esc(fmtDateTime(source.source_updated_at))}`:''} ${source.last_seen_at?`· Last seen ${esc(fmtDateTime(source.last_seen_at))}`:''}</div>${source.body?`<p>${esc(String(source.body).slice(0,500))}${String(source.body).length>500?'…':''}</p>`:''}</article>`;
}

function filterSources(state){
  const q=String(state.intelSearch||'').toLowerCase(),systems=state.intelSystem||'all',history=state.intelHistory||'current';
  return (state.raw.sourceRecords??[]).filter(s=>(state.projectScope==='all'||s.project_id===state.projectScope)&&(systems==='all'||s.source_system===systems)&&(history==='all'||(history==='historical'?s.is_historical:!s.is_historical))&&(!q||`${s.title||''} ${s.body||''} ${s.source_ref||''}`.toLowerCase().includes(q)));
}

export function renderIntelligence(ctx,root){
  const state=ctx.store.get(),rows=filterSources(state),systems=[...new Set((state.raw.sourceRecords??[]).map(s=>s.source_system).filter(Boolean))].sort();
  root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">SOURCE INTELLIGENCE</div><h1>Sources / Intelligence</h1><p>Raw Asana, Gmail, Todoist and imported evidence lives here until you deliberately promote it into management.</p></div></div><div class="sourceToolbar"><div class="searchWrap"><input data-intel-search value="${esc(state.intelSearch||'')}" placeholder="Search source titles, text or IDs…"></div><select data-intel-system><option value="all">All Sources</option>${systems.map(s=>`<option value="${esc(s)}" ${state.intelSystem===s?'selected':''}>${esc(sourceLabel(s))}</option>`).join('')}</select><select data-intel-history><option value="current" ${(state.intelHistory||'current')==='current'?'selected':''}>Current</option><option value="historical" ${state.intelHistory==='historical'?'selected':''}>Historical</option><option value="all" ${state.intelHistory==='all'?'selected':''}>Current + Historical</option></select></div><div class="resultBar"><strong>${rows.length}</strong> source record${rows.length===1?'':'s'}</div><div class="intelList">${rows.slice(0,500).map(s=>sourceRow(s,state)).join('')||'<div class="emptyState">No source records match this view.</div>'}</div>`;
  qs('[data-intel-search]',root).addEventListener('input',e=>{ctx.store.set({intelSearch:e.target.value});ctx.render()});qs('[data-intel-system]',root).addEventListener('change',e=>{ctx.store.set({intelSystem:e.target.value});ctx.render()});qs('[data-intel-history]',root).addEventListener('change',e=>{ctx.store.set({intelHistory:e.target.value});ctx.render()});qsa('[data-manage-item]',root).forEach(b=>b.addEventListener('click',()=>ctx.openItem(b.dataset.manageItem)));qsa('[data-promote-item]',root).forEach(b=>b.addEventListener('click',async()=>{const r=await ctx.api.saveManagement(b.dataset.promoteItem,{attention_state:'review',status:'needs_review',management_origin:'user',promoted_at:new Date().toISOString(),promoted_by:state.user.id,attention_reason:'Promoted from Source Intelligence'},state.user.id);if(r.error)return toast(r.error.message,{bad:true});toast('Promoted to Needs Review');await ctx.reload()}));
}
