import { projectWorkStats } from '../core/selectors.mjs';
import { nextMilestone, scheduleStats } from '../core/schedule-engine.mjs';
import { esc, fmtDate, human, qsa, todayIso } from '../ui/dom.mjs';

function jobCard(project,state){
  const today=todayIso(),work=projectWorkStats(state.records,{projectId:project.id,userId:state.user.id,today}),sched=scheduleStats(state.schedule,{today,projectId:project.id}),next=nextMilestone(state.schedule,{today,projectScope:project.id});
  const meaningful=(state.raw.activityEvents??[]).find(e=>e.project_id===project.id&&e.meaningful)?.summary;
  const sourceRows=(state.raw.sourceRecords??[]).filter(s=>s.project_id===project.id);const latestSeen=sourceRows.map(s=>s.last_seen_at).filter(Boolean).sort().at(-1);
  return `<article class="jobControlCard"><div class="jobCardTop"><div><div class="eyebrow">PROJECT</div><h2>${esc(project.name)}</h2></div><button class="btn primary" data-open-job="${esc(project.id)}">Open Job</button></div><div class="jobMetricGrid"><div><strong>${work.mine}</strong><span>My Active</span></div><div><strong>${work.assignedOut}</strong><span>Assigned Out</span></div><div><strong>${work.waiting}</strong><span>Waiting</span></div><div><strong>${sched.risks}</strong><span>Schedule Risk</span></div></div><div class="jobNext"><span>Next Milestone</span><strong>${next?`${esc(fmtDate(next.plannedDate))} — ${esc(next.title)}`:'No verified future milestone'}</strong>${next?.confidence?`<small>${esc(human(next.confidence))}</small>`:''}</div><div class="jobFoot"><div><span>Latest Meaningful Change</span><strong>${esc(meaningful||'No recent meaningful change captured')}</strong></div><div><span>Source Freshness</span><strong>${esc(latestSeen?new Date(latestSeen).toLocaleString():'No source sync timestamp')}</strong></div></div></article>`;
}

function detail(project,state){
  const today=todayIso(),work=projectWorkStats(state.records,{projectId:project.id,userId:state.user.id,today}),sched=scheduleStats(state.schedule,{today,projectId:project.id}),next=nextMilestone(state.schedule,{today,projectScope:project.id});
  const recent=(state.raw.activityEvents??[]).filter(e=>e.project_id===project.id&&e.meaningful).slice(0,5);
  return `<div class="pageHeader"><div><div class="eyebrow">PROJECT CONTROL PANEL</div><h1>${esc(project.name)}</h1><p>One management view across work, schedule, source intelligence and team ownership.</p></div></div><div class="jobDetailMetrics"><div class="metric"><strong>${work.mine}</strong><span>My Active</span></div><div class="metric"><strong>${work.assignedOut}</strong><span>Assigned Out</span></div><div class="metric"><strong>${work.waiting}</strong><span>Waiting / Chase</span></div><div class="metric"><strong>${work.review}</strong><span>Needs Review</span></div><div class="metric"><strong>${sched.risks}</strong><span>Schedule Risks</span></div><div class="metric"><strong>${sched.upcoming30}</strong><span>Next 30 Days</span></div></div><section class="projectHero"><div><span>Next Important Milestone</span><h2>${next?`${esc(fmtDate(next.plannedDate))} — ${esc(next.title)}`:'No verified future milestone loaded'}</h2>${next?`<p>${esc(next.floor||'')} ${next.category?`· ${esc(human(next.category))}`:''} · ${esc(human(next.confidence))}</p>`:''}</div><button class="btn primary" data-job-nav="calendar">Open Calendar</button></section><div class="jobNavGrid"><button data-job-nav="my_work"><strong>Work</strong><span>My actions and promoted management items</span></button><button data-job-nav="assigned_out"><strong>Assigned Out</strong><span>Work owned by other people</span></button><button data-job-nav="calendar"><strong>Calendar</strong><span>Cycle, lookahead and long-lead milestones</span></button><button data-job-nav="intelligence"><strong>Sources / Intelligence</strong><span>Asana, Gmail and imported evidence</span></button><button data-job-nav="changes"><strong>What Changed</strong><span>Meaningful source deltas</span></button><button data-job-nav="team"><strong>Field & Team</strong><span>Ownership and handoffs</span></button></div><section class="pageSection"><div class="sectionHeading"><div><h2>Recent Meaningful Changes</h2></div></div>${recent.length?`<div class="changeList">${recent.map(e=>`<div class="changeRow"><span>${esc(new Date(e.happened_at).toLocaleDateString())}</span><strong>${esc(e.summary)}</strong><small>${esc(human(e.confidence||'source_says'))}</small></div>`).join('')}</div>`:'<div class="emptyState">No meaningful changes captured yet.</div>'}</section>`;
}

export function renderJobs(ctx,root){
  const state=ctx.store.get();
  if(state.projectScope!=='all'){
    const project=state.maps.projects[state.projectScope];root.innerHTML=detail(project,state);qsa('[data-job-nav]',root).forEach(b=>b.addEventListener('click',()=>ctx.navigate(b.dataset.jobNav)));return;
  }
  const jobs=(state.raw.projects??[]).filter(p=>p.id!=='other-work');root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">ALL ACTIVE JOBS</div><h1>Jobs</h1><p>Compact control panels for the projects you actually manage.</p></div></div><div class="jobControlGrid">${jobs.map(p=>jobCard(p,state)).join('')}</div>`;qsa('[data-open-job]',root).forEach(b=>b.addEventListener('click',()=>ctx.setProject(b.dataset.openJob)));
}
