import { projectWorkStats } from '../core/selectors.mjs';
import { latestIntelligence } from '../core/intelligence-model.mjs';
import { nextMilestone, scheduleStats } from '../core/schedule-engine.mjs';
import { sourceBadge } from '../ui/source-panel.mjs';
import { esc, fmtDate, fmtDateTime, human, qsa, todayIso } from '../ui/dom.mjs';

function sourceCounts(project,state){const rows=(state.raw.sourceRecords??[]).filter(s=>s.project_id===project.id&&!s.is_historical),counts={};for(const s of rows)counts[s.source_system]=(counts[s.source_system]||0)+1;return counts}
function countsText(c){return Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${human(k)} ${v}`).join(' · ')||'No current source records'}
function activityCard(r){const s=r.primarySource;return`<article class="intelActivityCard"><div class="chipRow">${s?sourceBadge(s,{compact:true}):''}<span class="contextChip">${esc(r.categoryName||'Activity')}</span>${r.ownerName?`<span class="ownerChip">${esc(r.ownerName)}</span>`:''}</div><h3>${esc(r.title)}</h3>${r.description?`<p>${esc(String(r.description).slice(0,220))}${String(r.description).length>220?'…':''}</p>`:''}<div class="intelMeta">${esc(r.updatedAt?fmtDateTime(r.updatedAt):'')}</div><div class="rowActions">${r.linkedItemId?`<button class="btn small primary" data-manage-item="${esc(r.linkedItemId)}">Manage</button>`:''}${s?.resolvedUrl?`<a class="btn small secondary" href="${esc(s.resolvedUrl)}" target="_blank" rel="noopener noreferrer">${esc(s.actionLabel||'Open Original')}</a>`:''}</div></article>`}

function jobCard(project,state){const today=todayIso(),work=projectWorkStats(state.records,{projectId:project.id,userId:state.user.id,today}),sched=scheduleStats(state.schedule,{today,projectId:project.id}),next=nextMilestone(state.schedule,{today,projectScope:project.id}),meaningful=(state.raw.activityEvents??[]).find(e=>e.project_id===project.id&&e.meaningful)?.summary,counts=sourceCounts(project,state);return`<article class="jobControlCard"><div class="jobCardTop"><div><div class="eyebrow">PROJECT</div><h2>${esc(project.name)}</h2></div><button class="btn primary" data-open-job="${esc(project.id)}">Open Job</button></div><div class="jobMetricGrid"><div><strong>${work.mine}</strong><span>My Active</span></div><div><strong>${work.assignedOut}</strong><span>Assigned Out</span></div><div><strong>${sched.risks}</strong><span>Schedule Risk</span></div><div><strong>${Object.values(counts).reduce((a,b)=>a+b,0)}</strong><span>Current Sources</span></div></div><div class="jobNext"><span>Next Milestone</span><strong>${next?`${esc(fmtDate(next.plannedDate))} — ${esc(next.title)}`:'No verified future milestone'}</strong></div><div class="sourceCountLine">${esc(countsText(counts))}</div><div class="jobFoot"><div><span>Latest Meaningful Change</span><strong>${esc(meaningful||'No recent meaningful change captured')}</strong></div></div></article>`}

function detail(project,state){const today=todayIso(),work=projectWorkStats(state.records,{projectId:project.id,userId:state.user.id,today}),sched=scheduleStats(state.schedule,{today,projectId:project.id}),next=nextMilestone(state.schedule,{today,projectScope:project.id}),counts=sourceCounts(project,state),activity=latestIntelligence(state.intelligenceRecords,{projectScope:project.id,limit:16,excludeSystems:['todoist','command_center']});return`<div class="pageHeader"><div><div class="eyebrow">PROJECT CONTROL PANEL</div><h1>${esc(project.name)}</h1><p>Current work, Asana/Gmail activity, schedule, files and team ownership in one place.</p></div></div><div class="jobDetailMetrics"><div class="metric"><strong>${work.mine}</strong><span>My Active</span></div><div class="metric"><strong>${work.assignedOut}</strong><span>Assigned Out</span></div><div class="metric"><strong>${work.waiting}</strong><span>Waiting</span></div><div class="metric"><strong>${sched.risks}</strong><span>Schedule Risks</span></div><div class="metric"><strong>${Object.values(counts).reduce((a,b)=>a+b,0)}</strong><span>Current Sources</span></div></div><div class="sourceCountBanner"><strong>Connected project intelligence:</strong> ${esc(countsText(counts))}</div><section class="projectHero"><div><span>Next Important Milestone</span><h2>${next?`${esc(fmtDate(next.plannedDate))} — ${esc(next.title)}`:'No verified future milestone loaded'}</h2>${next?`<p>${esc(next.floor||'')} ${next.category?`· ${esc(human(next.category))}`:''} · ${esc(human(next.confidence))}</p>`:''}</div><button class="btn primary" data-job-nav="calendar">Open Calendar</button></section><section class="pageSection"><div class="sectionHeading"><div><h2>Current Project Activity</h2><p>Actual Asana, Gmail and file records — not converted into fake tasks.</p></div><button class="btn secondary" data-job-nav="intelligence">Open All Sources</button></div>${activity.length?`<div class="intelActivityGrid">${activity.map(activityCard).join('')}</div>`:'<div class="emptyState">No current project intelligence loaded yet.</div>'}</section><div class="jobNavGrid"><button data-job-nav="my_work"><strong>My Work</strong><span>Things you actually own</span></button><button data-job-nav="assigned_out"><strong>Assigned Out</strong><span>Work owned by other people</span></button><button data-job-nav="calendar"><strong>Calendar</strong><span>Cycle and long-lead milestones</span></button><button data-job-nav="intelligence"><strong>All Sources</strong><span>Every current source record</span></button><button data-job-nav="changes"><strong>What Changed</strong><span>Meaningful source deltas</span></button><button data-job-nav="team"><strong>Team</strong><span>Ownership and handoffs</span></button></div>`}

export function renderJobs(ctx,root){const state=ctx.store.get();if(state.projectScope!=='all'){const project=state.maps.projects[state.projectScope];root.innerHTML=detail(project,state);qsa('[data-job-nav]',root).forEach(b=>b.addEventListener('click',()=>ctx.navigate(b.dataset.jobNav)));qsa('[data-manage-item]',root).forEach(b=>b.addEventListener('click',()=>ctx.openItem(b.dataset.manageItem)));return}const jobs=(state.raw.projects??[]).filter(p=>p.id!=='other-work');root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">ALL ACTIVE JOBS</div><h1>Jobs</h1><p>Each job combines management work with its actual source-system intelligence.</p></div></div><div class="jobControlGrid">${jobs.map(p=>jobCard(p,state)).join('')}</div>`;qsa('[data-open-job]',root).forEach(b=>b.addEventListener('click',()=>ctx.setProject(b.dataset.openJob)))}
