import { filterRecords } from '../core/filter-engine.mjs';
import { latestIntelligence } from '../core/intelligence-model.mjs';
import { selectAssignedOut, selectMyWork, selectToday, selectWaiting, sortByUrgency } from '../core/selectors.mjs';
import { isScheduleRisk, selectUpcoming } from '../core/schedule-engine.mjs';
import { itemCard } from '../ui/item-card.mjs';
import { sourceBadge } from '../ui/source-panel.mjs';
import { esc, fmtDate, fmtDateTime, human, qs, qsa, todayIso } from '../ui/dom.mjs';
import { renderToolbar, wireToolbar, WORK_FILTER_DIMS } from '../ui/page-tools.mjs';

function cards(rows,empty='Nothing here.'){return rows.length?`<div class="cardGrid">${rows.map(r=>itemCard(r)).join('')}</div>`:`<div class="emptyState">${esc(empty)}</div>`}
function wireCards(root,onOpen){qsa('[data-manage-item]',root).forEach(b=>b.addEventListener('click',()=>onOpen(b.dataset.manageItem)))}
function filter(rows,state){return filterRecords(rows,state.viewState.filters,state.combinedUniverse||state.universe)}
function kpi(label,value){return`<div class="metric"><strong>${value}</strong><span>${esc(label)}</span></div>`}
function schedMini(m){return`<button class="scheduleMini" data-open-schedule="${esc(m.id)}"><div class="scheduleMiniDate">${esc(fmtDate(m.plannedDate))}</div><div><strong>${esc(m.title)}</strong><span>${esc(m.projectName||'')}${m.floor?` · ${esc(m.floor)}`:''}</span></div><span class="confidence ${esc(m.confidence)}">${esc(human(m.confidence))}</span></button>`}
function intelCard(r){const src=r.primarySource;return`<article class="intelActivityCard"><div class="intelActivityHead"><div class="chipRow">${src?sourceBadge(src,{compact:true}):''}<span class="contextChip">${esc(r.projectName||'No Job')}</span>${r.ownerName?`<span class="ownerChip">${esc(r.ownerName)}</span>`:''}${r.categoryName?`<span class="contextChip">${esc(r.categoryName)}</span>`:''}</div><span class="smallMuted">${esc(r.updatedAt?fmtDateTime(r.updatedAt):'')}</span></div><h3>${esc(r.title)}</h3>${r.description?`<p>${esc(String(r.description).slice(0,260))}${String(r.description).length>260?'…':''}</p>`:''}<div class="rowActions">${r.linkedItemId?`<button class="btn small primary" data-manage-item="${esc(r.linkedItemId)}">Manage</button>`:''}${src?.resolvedUrl?`<a class="btn small secondary" href="${esc(src.resolvedUrl)}" target="_blank" rel="noopener noreferrer">${esc(src.actionLabel||'Open Original')}</a>`:''}</div></article>`}
function intelList(rows){return rows.length?`<div class="intelActivityGrid">${rows.map(intelCard).join('')}</div>`:'<div class="emptyState">No source activity matches this view.</div>'}

export function renderToday(ctx,root){
  const state=ctx.store.get(),today=todayIso();
  const managed=selectToday(state.records,{userId:state.user.id,today,projectScope:state.projectScope});
  const assignedSource=state.intelligenceRecords.filter(r=>(state.projectScope==='all'||r.project===state.projectScope)&&r.assignedToCurrentUser);
  const rows=sortByUrgency(filter([...managed,...assignedSource],state),today);
  const waiting=filter(selectWaiting(state.records,{userId:state.user.id,projectScope:state.projectScope,mineOrWatched:true}),state).filter(r=>r.followUp&&r.followUp<=today);
  const upcoming=selectUpcoming(state.schedule,{today,days:21,projectScope:state.projectScope}).slice(0,8);
  const risks=state.schedule.filter(m=>(state.projectScope==='all'||m.project===state.projectScope)&&isScheduleRisk(m,today)).slice(0,8);
  const assignedOut=selectAssignedOut(state.records,{userId:state.user.id,projectScope:state.projectScope});
  const activity=filter(latestIntelligence(state.intelligenceRecords,{projectScope:state.projectScope,limit:80,excludeSystems:['todoist','command_center']}),state).slice(0,16);
  root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">${state.projectScope==='all'?'ALL JOBS':esc(state.maps.projects[state.projectScope]?.name||state.projectScope)}</div><h1>Today</h1><p>Your actions plus the latest real project activity from Asana, Gmail, schedules and files.</p></div><button class="btn primary" data-add-work>+ Add Work</button></div>${renderToolbar(state,{page:'today',placeholder:'Search actions and project activity…',dimensions:WORK_FILTER_DIMS})}<div class="metricGrid">${kpi('Needs Attention',rows.length)}${kpi('Chase Today',waiting.length)}${kpi('Schedule Risks',risks.length)}${kpi('Assigned Out',assignedOut.length)}</div><section class="pageSection"><div class="sectionHeading"><div><h2>My Action Items</h2><p>Todoist, Command Center, and any Asana work actually assigned to you.</p></div></div>${cards(rows,'No action items match this view.')}</section><section class="pageSection"><div class="sectionHeading"><div><h2>Latest Project Activity</h2><p>Current Asana, Gmail and file intelligence. These are not fake tasks; they are the actual project records.</p></div><button class="btn secondary" data-go-sources>Open All Sources</button></div>${intelList(activity)}</section><div class="twoCol"><section class="pageSection"><div class="sectionHeading"><h2>Waiting / Chase</h2></div>${cards(waiting,'Nothing needs chasing today.')}</section><section class="pageSection"><div class="sectionHeading"><h2>Schedule Risks</h2></div>${risks.length?`<div class="scheduleMiniList">${risks.map(schedMini).join('')}</div>`:'<div class="emptyState">No current schedule risks.</div>'}</section></div><section class="pageSection"><div class="sectionHeading"><div><h2>Coming Up</h2></div><button class="btn secondary" data-go-calendar>Open Calendar</button></div>${upcoming.length?`<div class="scheduleMiniList">${upcoming.map(schedMini).join('')}</div>`:'<div class="emptyState">No dated milestones in the next 21 days.</div>'}</section>`;
  wireToolbar({root,state,store:ctx.store,api:ctx.api,page:'today',dimensions:WORK_FILTER_DIMS,onChange:ctx.render});wireCards(root,ctx.openItem);qs('[data-go-calendar]',root)?.addEventListener('click',()=>ctx.navigate('calendar'));qs('[data-go-sources]',root)?.addEventListener('click',()=>ctx.navigate('intelligence'));qs('[data-add-work]',root)?.addEventListener('click',ctx.addWork);qsa('[data-open-schedule]',root).forEach(b=>b.addEventListener('click',()=>ctx.openSchedule(b.dataset.openSchedule)));
}

export function renderMyWork(ctx,root){
  const state=ctx.store.get(),today=todayIso(),managed=selectMyWork(state.records,{userId:state.user.id,projectScope:state.projectScope}),assignedSource=state.intelligenceRecords.filter(r=>(state.projectScope==='all'||r.project===state.projectScope)&&r.assignedToCurrentUser),rows=sortByUrgency(filter([...managed,...assignedSource],state),today);
  root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">${state.projectScope==='all'?'ALL JOBS':esc(state.maps.projects[state.projectScope]?.name||state.projectScope)}</div><h1>My Work</h1><p>Work you own here plus source-system work actually assigned to you.</p></div><button class="btn primary" data-add-work>+ Add Work</button></div>${renderToolbar(state,{page:'my_work',placeholder:'Search my work…',dimensions:WORK_FILTER_DIMS})}<div class="resultBar"><strong>${rows.length}</strong> matching item${rows.length===1?'':'s'}</div>${cards(rows,'No work matches this view.')}`;
  wireToolbar({root,state,store:ctx.store,api:ctx.api,page:'my_work',dimensions:WORK_FILTER_DIMS,onChange:ctx.render});wireCards(root,ctx.openItem);qs('[data-add-work]',root)?.addEventListener('click',ctx.addWork);
}

export function renderAssigned(ctx,root){const state=ctx.store.get(),today=todayIso(),base=selectAssignedOut(state.records,{userId:state.user.id,projectScope:state.projectScope}),rows=sortByUrgency(filter(base,state),today),groups=new Map();for(const r of rows){const k=r.ownerName||'Unassigned';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}root.innerHTML=`<div class="pageHeader"><div><div class="eyebrow">${state.projectScope==='all'?'ALL JOBS':esc(state.maps.projects[state.projectScope]?.name||state.projectScope)}</div><h1>Assigned Out</h1><p>Active Command Center work owned by someone else.</p></div></div>${renderToolbar(state,{page:'assigned_out',placeholder:'Search assigned work…',dimensions:WORK_FILTER_DIMS})}<div class="resultBar"><strong>${rows.length}</strong> matching item${rows.length===1?'':'s'}</div>${rows.length?[...groups].map(([name,list])=>`<section class="ownerGroup"><div class="ownerGroupHead"><h2>${esc(name)}</h2></div>${cards(list)}</section>`).join(''):'<div class="emptyState">No assigned-out work matches this view.</div>'}`;wireToolbar({root,state,store:ctx.store,api:ctx.api,page:'assigned_out',dimensions:WORK_FILTER_DIMS,onChange:ctx.render});wireCards(root,ctx.openItem)}
