import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { CONFIG } from './config.mjs';
import { createDataApi } from './data-api.mjs';
import { createStore } from './store.mjs';
import { restorePageDefault } from './ui/page-tools.mjs';
import { closeModal, esc, fmtDate, human, openModal, qs, qsa, toast } from './ui/dom.mjs';
import { openItemDetail } from './ui/item-detail.mjs';
import { sourceList } from './ui/source-panel.mjs';
import { renderToday, renderMyWork, renderAssigned } from './pages/work-pages.mjs';
import { renderJobs } from './pages/jobs.mjs';
import { renderCalendar } from './pages/calendar.mjs';
import { renderIntelligence } from './pages/intelligence.mjs';
import { renderChanges } from './pages/changes.mjs';
import { renderTeam } from './pages/team.mjs';
import { renderDiagnostics } from './pages/diagnostics.mjs';

const sb=createClient(CONFIG.supabaseUrl,CONFIG.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const api=createDataApi(sb,CONFIG.workspaceId);const store=createStore();
const PAGE_LABELS={today:'Today',my_work:'My Work',assigned_out:'Assigned Out',jobs:'Jobs',calendar:'Calendar',intelligence:'Sources',changes:'What Changed',team:'Team',diagnostics:'Diagnostics'};
const PAGE_ICONS={today:'⌂',my_work:'✓',assigned_out:'→',jobs:'▦',calendar:'▣',intelligence:'◫',changes:'↻',team:'♟',diagnostics:'⚙'};
const BUILTIN_DEFAULTS={
  intelligence:{filters:{search:'',include:{sourceState:['current']},exclude:{},date:{}}},
  changes:{filters:{search:'',include:{meaningful:['meaningful']},exclude:{},date:{}}},
};
function builtIn(page){return BUILTIN_DEFAULTS[page]||{}}

function app(){return document.querySelector('#app')}
function renderLoading(text='Loading Command Center…'){app().innerHTML=`<div class="bootV3"><div class="logoV3">EA</div><strong>${esc(text)}</strong></div>`}
function renderAuth(){app().innerHTML=`<div class="authV3"><div class="authCardV3"><div class="brandV3"><div class="logoV3">EA</div><div><strong>Eastern Air</strong><span>COMMAND CENTER V3</span></div></div><h1>Sign in</h1><p>Private management layer above your project systems.</p><div id="authNotice"></div><label>Email<input id="authEmail" type="email"></label><label>Password<input id="authPass" type="password"></label><button class="btn primary full" id="authLogin">Sign in</button></div></div>`;qs('#authLogin').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:qs('#authEmail').value.trim(),password:qs('#authPass').value});if(error)qs('#authNotice').innerHTML=`<div class="errorPanel">${esc(error.message)}</div>`};}
function renderNoAccess(){app().innerHTML=`<div class="authV3"><div class="authCardV3"><h1>No workspace access</h1><p>This login is not an active Eastern Air Command Center member.</p><button class="btn secondary full" id="noAccessLogout">Sign out</button></div></div>`;qs('#noAccessLogout').onclick=()=>sb.auth.signOut();}

async function loadAll(user){const membership=await api.getMembership(user.id);if(membership.error||!membership.data)return renderNoAccess();const loaded=await api.loadWorkspace(user.id);store.load({user,member:membership.data,raw:loaded.raw,errors:loaded.errors});store.set({page:'today',projectScope:'all',viewState:restorePageDefault(store.get(),'today',builtIn('today'))});renderShell();}
async function reload(){const s=store.get(),loaded=await api.loadWorkspace(s.user.id);store.refreshRaw(loaded.raw,loaded.errors);render();}

function navItems(state){const keys=['today','my_work','assigned_out','jobs','calendar','intelligence','changes','team'];if(state.member.role==='admin')keys.push('diagnostics');return keys.map(k=>`<button class="sideNavBtn ${state.page===k?'active':''}" data-nav-page="${k}"><span>${PAGE_ICONS[k]}</span>${PAGE_LABELS[k]}</button>`).join('')}
function projectChips(state){return `<button class="projectChip ${state.projectScope==='all'?'active':''}" data-project-scope="all">All Jobs</button>${(state.raw.projects??[]).filter(p=>p.id!=='other-work').map(p=>`<button class="projectChip ${state.projectScope===p.id?'active':''}" data-project-scope="${esc(p.id)}">${esc(p.name.replace(' Street',''))}</button>`).join('')}`}
function renderShell(){const state=store.get(),moreActive=!['today','my_work','jobs','calendar'].includes(state.page);app().innerHTML=`<div class="appShellV3"><aside class="sidebarV3"><div class="brandV3 sidebarBrand"><div class="logoV3">EA</div><div><strong>Command Center</strong><span>V3 REBUILD</span></div></div><nav class="sideNav">${navItems(state)}</nav><div class="sidebarFoot"><span>${esc(state.user.email||'')}</span><small>${esc(state.member.role)} · ${esc(CONFIG.build)}</small><button class="linkBtn" data-logout>Sign out</button></div></aside><header class="topbarV3"><div class="mobileBrand"><div class="logoV3 small">EA</div><strong>Command Center</strong></div><div class="projectStrip">${projectChips(state)}</div></header><main class="contentV3" id="pageRoot"></main><nav class="mobileNav">${['today','my_work','jobs','calendar'].map(k=>`<button data-nav-page="${k}" class="${state.page===k?'active':''}"><span>${PAGE_ICONS[k]}</span>${PAGE_LABELS[k]}</button>`).join('')}<button data-mobile-more class="${moreActive?'active':''}"><span>•••</span>More</button></nav></div>`;wireShell();render();}
function wireShell(){qsa('[data-nav-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.navPage)));qsa('[data-project-scope]').forEach(b=>b.addEventListener('click',()=>setProject(b.dataset.projectScope)));qs('[data-logout]')?.addEventListener('click',()=>sb.auth.signOut());qs('[data-mobile-more]')?.addEventListener('click',openMobileMore)}
function navigate(page){const state=store.get();store.set({page,viewState:restorePageDefault({...state,page},page,builtIn(page))});renderShell();}
function setProject(projectScope){const state=store.get();store.set({projectScope,viewState:restorePageDefault({...state,projectScope},state.page,builtIn(state.page))});renderShell();}
function openMobileMore(){const s=store.get(),keys=['assigned_out','intelligence','changes','team'];if(s.member.role==='admin')keys.push('diagnostics');const panel=openModal(`<div class="modalHeader"><div><h2>More</h2><p>Additional Command Center views.</p></div><button class="iconBtn" data-close-modal>×</button></div><div class="mobileMoreGrid">${keys.map(k=>`<button class="mobileMoreItem" data-more-page="${k}"><span>${PAGE_ICONS[k]}</span><strong>${PAGE_LABELS[k]}</strong></button>`).join('')}</div>`);qsa('[data-more-page]',panel).forEach(b=>b.addEventListener('click',()=>{closeModal();navigate(b.dataset.morePage)}));}

const ctx={store,api,reload,navigate,setProject,render,renderShell,openItem,openSchedule,openScheduleDay,addWork};
function render(){const state=store.get(),root=qs('#pageRoot');if(!root)return;document.querySelectorAll('.sideNavBtn,[data-nav-page]').forEach(b=>b.classList.toggle('active',b.dataset.navPage===state.page));if(state.page==='today')renderToday(ctx,root);else if(state.page==='my_work')renderMyWork(ctx,root);else if(state.page==='assigned_out')renderAssigned(ctx,root);else if(state.page==='jobs')renderJobs(ctx,root);else if(state.page==='calendar')renderCalendar(ctx,root);else if(state.page==='intelligence')renderIntelligence(ctx,root);else if(state.page==='changes')renderChanges(ctx,root);else if(state.page==='team')renderTeam(ctx,root);else if(state.page==='diagnostics')renderDiagnostics(ctx,root);}

async function openItem(id){const record=store.get().records.find(r=>r.id===id);if(!record)return toast('Item not found',{bad:true});await openItemDetail({record,store,api,onReload:reload});}
function scheduleDetail(m){const source=m.sourceRecordId?store.get().maps.sources[m.sourceRecordId]:null;return `<div class="modalHeader"><div><div class="eyebrow">${esc(m.projectName||'')}</div><h2>${esc(m.title)}</h2></div><button class="iconBtn" data-close-modal>×</button></div><div class="scheduleDetailGrid"><div><span>Planned</span><strong>${esc(m.plannedDate?fmtDate(m.plannedDate,{year:true}):'TBD')}</strong></div><div><span>Status</span><strong>${esc(human(m.status))}</strong></div><div><span>Confidence</span><strong>${esc(human(m.confidence))}</strong></div><div><span>Date Type</span><strong>${esc(human(m.dateType))}</strong></div><div><span>Floor / Area</span><strong>${esc(m.floor||'—')}</strong></div><div><span>Category</span><strong>${esc(human(m.category||'—'))}</strong></div></div>${m.notes?`<div class="detailSection"><strong>Notes</strong><p>${esc(m.notes)}</p></div>`:''}<div class="detailSection"><strong>Schedule Source</strong>${source?sourceList([{...source,isPrimary:true,resolvedUrl:source.source_url,badge:human(source.source_system),actionLabel:'Open Original'}]):`<div class="emptyInline">Source provenance is not attached to this milestone yet.</div>`}</div>`}
function openSchedule(id){const m=store.get().schedule.find(x=>x.id===id);if(!m)return;openModal(scheduleDetail(m),{wide:true})}
function openScheduleDay(date,rows){openModal(`<div class="modalHeader"><div><div class="eyebrow">CALENDAR</div><h2>${esc(new Date(`${date}T12:00:00`).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'}))}</h2></div><button class="iconBtn" data-close-modal>×</button></div>${rows.length?rows.map(m=>`<button class="milestoneRow" data-day-milestone="${esc(m.id)}"><div class="milestoneMain"><strong>${esc(m.title)}</strong><span>${esc(m.projectName||'')} ${m.floor?`· ${esc(m.floor)}`:''}</span></div></button>`).join(''):'<div class="emptyState">No milestones.</div>'}`,{wide:true});qsa('[data-day-milestone]').forEach(b=>b.addEventListener('click',()=>{closeModal();openSchedule(b.dataset.dayMilestone)}))}

function addWork(){const s=store.get(),projects=s.raw.projects??[],categories=s.raw.categories??[],people=s.raw.people??[];const panel=openModal(`<div class="modalHeader"><div><h2>Add Work</h2><p>Creates an Eastern Air management item only. No source system is edited.</p></div><button class="iconBtn" data-close-modal>×</button></div><label>What needs to happen?<input id="awTitle"></label><div class="formGrid2"><label>Job<select id="awProject">${projects.map(p=>`<option value="${esc(p.id)}" ${s.projectScope===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Category<select id="awCategory">${categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><label>Priority<select id="awPriority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label><label>Due<input id="awDue" type="date"></label></div><label>Owner<select id="awOwner"><option value="">Unassigned</option>${people.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label>Notes<textarea id="awDesc"></textarea></label><button class="btn primary full" id="awSave">Add to Command Center</button>`,{wide:true});qs('#awSave',panel).onclick=async()=>{const title=qs('#awTitle',panel).value.trim();if(!title)return toast('Add a title',{bad:true});const r=await api.createCommandItem(s.user.id,{projectId:qs('#awProject',panel).value,title,description:qs('#awDesc',panel).value.trim()||null,categoryId:qs('#awCategory',panel).value,priority:qs('#awPriority',panel).value,due:qs('#awDue',panel).value||null,ownerPersonId:qs('#awOwner',panel).value||null});if(r.error)return toast(r.error.message,{bad:true});toast('Work added');closeModal();await reload()}}

async function init(){renderLoading();const {data}=await sb.auth.getSession();if(data.session?.user)await loadAll(data.session.user);else renderAuth();}
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')renderAuth();if(event==='SIGNED_IN'&&session?.user)setTimeout(()=>loadAll(session.user),0)});
init();
